### ISSUE TITLE
client : all API must be called again all shards

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#114]
It currently only use multiple shards when there is distribution/replication pipe

**Comment by iwanbk** [comment]
# Client spesification

## Library

The library takes following configuration:
- 0-server server shards
- meta server shards
- IYO credential
- namespace and organization
- pipes if needed


### Object creation and get

Object creation and get is normally only called against single 0-stor server.
But depend on the configured pipes, this kind of method might be called against multiple servers at a time. It happens when
there is distribution / replication in the pipe.

**object creation**

create object in 0-stor server:

- client select random server to store the data. If selected server is failed, it tries another server
- when previous key is given and metadata/etc is used, it needs to build linked list of metadata by connecting the `next` and `prev` field of the metadata

errors is list of 0-stor servers which were down, if `errors != nil` then a repair is needed to fix the store

**object get**

client select the server based on the info in metadata

#### Other 0-stor APIs

It is methods that call all 0-stor APIs other than object creation & get.

It has to be called concurrently against all server and returns `map[string]APIReturnValue`:

- `APIReturnValue` is the 0-stor API return value and `error` if needed
-  Key of the map is the 0-stor server address.

### Pipes

User can configure pipes which process the data before uploaded to the server. If used to upload the data, the pipe also needed to download the data.

Supported pipe components:
- encrypt
- compress
- distribution / erasure encoding
- replication
- chunker

If there is no configured pipe, client library need to add 0-stor client as the default pipe.


### Walk

if there is linked list in the metadata, client could walk over the linked list and get the object stored

### Check

#will let us know if all parts of the erasure coded or replicated items are there

### Repair

will walk over the linked list and check if all items are there, basically do `check` of each item.
if issue found then will re-encode and fix the missing part(s) and rewrite the metadata (release nr up)


### Namespace methods

Methods related to namespace:

- DeleteNamespace
- CreateJWT
- GivePermission
- RemovePermission
- GetPermission

## Daemon

TODO

**Comment by iwanbk** [comment]
@zaibon it is in `Other 0-stor APIs` of the previous comment.

If you're OK, i can send above comment as specification draft

**Comment by zaibon** [comment]
Looks good

**Comment by iwanbk** [comment]
It is only `Other 0-stor APIs` part that left to be implemented

**Comment by zaibon** [comment]
Repair is still in progress too, see https://github.com/zero-os/0-stor/tree/repair

**Comment by iwanbk** [comment]
> It is only Other 0-stor APIs part that left to be implemented

For this part, it is `ObjectExist` and `GetNamespace`

**Comment by iwanbk** [comment]
obsoleted by new client design
