### ISSUE TITLE
encrypt : fix encryption key

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#126]
Need to use hash of the content, instead of same key for all data.

**Comment by zaibon** [comment]
```go
encryptConf := encrypt.Config{
    Type:    encrypt.TypeAESGCM,
    PrivKey: "ab345678901234567890123456789012",
    Nonce:   "123456789012",
  }
```
The nonce shouldn't be given by the user, instead it should be randomly generated each time you encrypt a piece of data, and it can just be concatted to the encrypted content, which the std algo supports if you give the nonce as the first key.

You can find an example of that in https://github.com/gtank/cryptopasta/blob/master/encrypt.go#L37-L55, written by a security expert

**Comment by iwanbk** [comment]
depend on #142

**Comment by zaibon** [comment]
Fix for the encrypt package : https://github.com/zero-os/0-stor/commit/c7fdc67b34dabcb3affd431426b06f808b02426e

**Comment by iwanbk** [comment]
> Need to use hash of the content, instead of same key for all data.

@zaibon still need to implement this, in regards to issue brought up by glen : private key in metadata is not secure, better to stick with current way

**Comment by zaibon** [comment]
I think we can keep it as it is for now. I'll close this one. we can still re-open if we need to
