### ISSUE TITLE
make etcd optional for object creation and get

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#128]
It currently always needed because because both methods support multiple server while only create/get to single server.

We can make it optional when there is only one configured shard

**Comment by zaibon** [comment]
The need of an extra database to store metadata should be optional. If the policy doesn't specify any metadata server, then the metadata should only be returned to the client after each write calls of the client.

**Comment by GlenDC** [comment]
Once we allow the user to create a client using its own Meta client, we can also make the client Meta optional by simply having it as `nil`. All public methods that assume a meta client exist (as to read/write metadata using a given key), should however return an error when no client is defined/given.

**Comment by GlenDC** [comment]
This issue is no longer valid.

Metastor clients will from now on always be required for the 0-stor master client, but it doesn't have to be ETCD (see #419 for example).
