### ISSUE TITLE
client : round trip test

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#138]
servers:
- start in memory 0-stor servers

client:
- create pipe with 0-stor integration
- write data through the pipe
- read data back

**Comment by zaibon** [comment]
I started writting a memory implementation of the db.DB interface for the same kind of purpose : 
https://gist.github.com/zaibon/8ad83bebb2092ed13a3bb5d5ea0406d3
Probably a few bugs in and there though

**Comment by iwanbk** [comment]
cool.

but please note that we on disk implementation is enough for unit test.
But in memory is certainly better in term of speed and no need to cleanup db dir after test

**Comment by zaibon** [comment]
ha ok, I though you wanted a full in memory key value store cause you said `start in memory 0-stor servers` but yeah disk is good enough.

**Comment by zaibon** [comment]
fixed in https://github.com/zero-os/0-stor/commit/103c890ee6623575d00db0e8d190cd1b1952579b
