### ISSUE TITLE
Issue with vendoring

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#144]
I need to update the `vendor` dir buth current vendoring is confusing:

- `vendor` dir is in root directory, while Godeps dir exist in `server`
- there is `vendor/vendor.json` file, AFAIK vendor.json 

@zaibon @Hamdy please update the docs related to vendoring strategy

**Comment by iwanbk** [comment]
Proposed solution at #144

**Comment by zaibon** [comment]
So far I used https://github.com/kardianos/govendor to managed the vendor folder. 

The Godep directory in server need to be removed since it's not used anywhere.
