### ISSUE TITLE
0-stor: create python client

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#15]
Find a way to use the 0-stor-lib from python.
What could be done is creating a small CLI on top the 0-stor-lib that we can call from python.

**Comment by despiegk** [comment]
I think better way is zerostor_command line is run as daemon
and then from e.g. grpc we instruct the daemon to upload, download, ..
so client is daemon which can be called from python, ...
little bit like IPFS

**Comment by despiegk** [comment]
make sure we have python client in js93+ using grpc, well documented

features
- low level (upload data directly)
- high level: upload file from path, ...
- with or without metadata

**Comment by zaibon** [comment]
Blocked on #68

**Comment by zaibon** [comment]
#68 is done. We can now finish this one.

**Comment by zaibon** [comment]
fixed in https://github.com/zero-os/0-stor/commit/565b114a5906cbf07c5541c7b59a26700675bc13
