### ISSUE TITLE
Incorrect error message using the 0stor-cli

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-stor#157]
# Scenario
1- Give a user all permissions to a certain namespace "peter"
![p11](https://user-images.githubusercontent.com/15011431/29315840-9c2b26d2-81c5-11e7-872f-a551dd409f5d.png)
2- Remove delete  permission of that user to this namspace using 0stor-cli
![p22](https://user-images.githubusercontent.com/15011431/29315841-9da113dc-81c5-11e7-9f38-e4d1ea20c241.png)
3- The delete permission is gone 
![p33](https://user-images.githubusercontent.com/15011431/29315844-9f6a8c70-81c5-11e7-8298-4126eda8a0b4.png)
## Expected result 
The error message given (in step 2) is incorrect

**Comment by zaibon** [comment]
The error message shows a bad response from IYO. Need to check why

**Comment by zaibon** [comment]
We should reformat the error printed to the user and format it properly.

**Comment by chrisvdg** [comment]
@zaibon , any suggestions for the formatting?

**Comment by chrisvdg** [comment]
@zaibon, also for this issue just reformat the error message as it's IYO that gives the bad response?

**Comment by zaibon** [comment]
@chrisvdg we need to make sure we don't have a bug in our end cause IYO should not return a bad response. 

And in any case we should have a proper error message displayed to the client. For both case where we have a bad response from IYO or if the operation failed for any reason.

**Comment by chrisvdg** [comment]
The 409 actually comes from sending an invite to  a user who is already a member of the namespace.
the error that came along was from the go IYOClient trying to Json decode the `Conflict` response body and has been reported to Lee.
