### ISSUE TITLE
client installation readme file 

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#158]
Can't install client by following those instructions https://github.com/zero-os/0-stor/blob/master/client/cmd/cli/README.md#installation

It should be replaced by:
```bash
 go get -u github.com/zero-os/0-stor/client/cmd/cli
```

**Comment by iwanbk** [comment]
Fixed by 9faffb15bddda57e4eb75271c07ec32a6c88414a

**Comment by iwanbk** [comment]
@zaibon @Hamdy @islamTaha12  does `go get` respect `vendor` directory when used to install binary like this?

**Comment by zaibon** [comment]
@iwanbk I just did the test, it use the lib from the vendor directory indeed. So it's all good

**Comment by islamTaha12** [comment]
fixed https://github.com/zero-os/0-stor/commit/eb2c6fcd78c8722373c8e34a129031e8273421d8
