### ISSUE TITLE
The downloaded file form 0stor is empty 

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-stor#160]
Two  servers are created on the left side of the screen (one of them is the etcd) .. i uploaded one file (as shown in the down right corner) and when i downloaded, it was empty as shown in the up right corner. 
![sc11](https://user-images.githubusercontent.com/15011431/29320192-bda30170-81d6-11e7-9fcf-f587fef17836.png)

**Comment by islamTaha12** [comment]
I think it didn't upload the file.
https://github.com/zero-os/0-stor/issues/161

**Comment by iwanbk** [comment]
@john-kheir could you rebuild and retry the test?
There was bug that prevent the error to be printed, just fixed at #154

**Comment by islamTaha12** [comment]
verified a19fec7
