### ISSUE TITLE
validateJWT might take too much CPU

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#162]
While debugging test problem described at https://github.com/zero-os/0-Disk/issues/311#issuecomment-322694804, i found that `validateJWT` might take too much CPU time.

See attached profiling results

tlogclient test profiling result
[cpu-tlogclient-test.pdf](https://github.com/zero-os/0-stor/files/1227554/cpu-tlogclient-test.pdf)

tlogserver test profiling result
[cpu-tlogserver-test.pdf](https://github.com/zero-os/0-stor/files/1227555/cpu-tlogserver-test.pdf)

**Comment by iwanbk** [comment]
majority of CPU time was taken by `validateJWT`

**Comment by zaibon** [comment]
Idea to solve the problem :
We could keep a certain number (TBD) of jwt token in memory. When a new request comes in, we check if we have the token in memory, if no, we decode the jwt and validate the request, then save in memory, if yes, we just accept the request cause the validation is already done.

of course the jwt should be kept in memory for only the time the token is valid. so they need to be automatically invalidated.

Maybe keeping in as key in badger would be fast enough if we allow  the key in badger to be the size of a jwt.Badger would keep it in memory anyway. Needs to test and see what works.

**Comment by iwanbk** [comment]
I propose to use LRU cache like https://github.com/karlseguin/ccache or https://github.com/hashicorp/golang-lru.

The advantage is:
- full in memory, no need to keep on disk cache
- has builtin cache timeout
- we can limit the amount of entries we want to keep
- it is LRU cache, least recently used entries will be deleted upon cache full

**Comment by iwanbk** [comment]
a WIP can be found on `jwt-cache` branch.
- use JWT expiration field as cache expiration
- stored information : 
      - validity
      - scopes
- only added in `grpc` because `rest` support will be dropped

next: 
   - benchmark test, still not sure the best way to do it
   - `exp` field in token claims seems to be in invalid format https://github.com/zero-os/0-stor/commit/fba0ebf7640cbdde403775aa4f41ead3916f37f7#diff-6a9c086b880d9611151f823cca987f48R81 , Lee is checking it

At first i use https://github.com/hashicorp/golang-lru which looks more popular but then moved to  https://github.com/karlseguin/ccache because golang-lru doesn't provide expiration feature.
