### ISSUE TITLE
Uploading the file to not existing namespace returns 201

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#163]
**Description**
Uploading the file to not existing namespace returns 201.

**Steps**
- Change namespace in the config file with a not exist name space
- Upload file 
- Check the server side response 
- Check iyo organization's structure

**Actual result**
![image](https://user-images.githubusercontent.com/17981089/29358033-f39ec8a6-8279-11e7-8319-3a3351cdf7c7.png)

![image](https://user-images.githubusercontent.com/17981089/29358053-034039f2-827a-11e7-9b89-2694cab3a07b.png)

**Comment by zaibon** [comment]
Seems there is a bug in IYO that always give scope of a sub organization even if it doesn't exists: https://github.com/itsyouonline/identityserver/issues/593

**Comment by zaibon** [comment]
Issue has been fixed on ItYou.online.

**Comment by chrisvdg** [comment]
I'm getting the following output, which I assume is expected to happen?
![screenshot from 2017-11-07 16-37-41](https://user-images.githubusercontent.com/23582741/32502137-3e310176-c3da-11e7-8232-2f79d2579648.png)

**Comment by zaibon** [comment]
@chrisvdg indeed, this issue has been fixed. it has the `state_verification` label

**Comment by chrisvdg** [comment]
Oh, I thought it still needed to be verified as it was still open

**Comment by GlenDC** [comment]
@islamTaha12 can you please verify and close it if indeed fixed. Also whoever is responsible should probably add an end-to-end test for this case, so it remains fixed.

**Comment by islamTaha12** [comment]
fixed
`
Version: 1.1.0-beta-2
Build: 314b863 2017-12-03T18:06:44+0200
Runtime: go1.9 linux
`

**Comment by islamTaha12** [comment]
I added a new test case to cover it 
```bash
nosetests-3.4 -vs test_suite/test_cases/basic_tests/test01_basic_tests.py:BasicTestCases.test010_upload_file_to_non_existing_namespace --tc-file test_suite/config.ini --tc=main.number_of_files:1
 [*] Create : 1 files under /tmp/upload 
ZST-010 ... 

 [*] uploading config path : /tmp/config_b03f690d65.yaml
 [*] Number of writer threads : 1
ok

----------------------------------------------------------------------
Ran 1 test in 1.724s

OK

```
