### ISSUE TITLE
Improve write performace by batching the writes

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#172]
From the badger README: 
>My writes are really slow. Why?
You're probably doing writes serially, using Set. To get the best write performance, use BatchSet, and call it concurrently from multiple goroutines.

We should investigate a way where we can batch a few writes together and write them concurrently using `BatchSet` instead of seriale write using `Set`

**Comment by iwanbk** [comment]
It seems we need new API for this.
BatchObjectsCreate?

**Comment by zaibon** [comment]
I see two options here.

- we add an API client side and let the client decide when to use the batch. But then, can't we be smart and add some logic that look if we are going to write multiple object to the same store, and then automatically sending all the object as one batch ?

- No new API client side, but some kind of buffering server side, that dump a batch of request after we reach a buffer size or after a certain time. But this solution requires to have some precaution in case of crash of the server to ensure we don't have data loss

**Comment by iwanbk** [comment]
> But then, can't we be smart and add some logic that look if we are going to write multiple object to the same store, and then automatically sending all the object as one batch ?

I'm afraid that this smart version will be slower.
Because this smart version will need to wait for some amount of time, see if there is another data to be included in the batch. It is the waiting that make it slower.

Instead of make it smarter, i prefer to make it configurable, still not sure how the configuration will be.


> No new API client side, but some kind of buffering server side, that dump a batch of request after we reach a buffer size or after a certain time. But this solution requires to have some precaution in case of crash of the server to ensure we don't have data loss

We don't have stupid/simple server anymore.

**Comment by zaibon** [comment]
now that we use 0-db, this is not relevant anymore
