### ISSUE TITLE
Update CLI to return the metadata after uploading a file

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#180]
Like the go client API has, the CLI should also return the metaadata created after a write operation.

**Comment by iwanbk** [comment]
What for? to print it to the console?

**Comment by zaibon** [comment]
Yep. The problem is currently QA is writing test scenarios. They use python for their work. Since we don't have python client yet,they only use the cli. But the cli doesn't return any Metadata. So it's hard for them to implement proper tests since they don't know where the data has been put. 

So or we return the Metadata after each upload. Or we add a command that return the Metadata for a certain key. The output should be something easily parsable to make their life easier

**Comment by zaibon** [comment]
Yep. The problem is currently QA is writing test scenarios. They use python for their work. Since we don't have python client yet,they only use the cli. But the cli doesn't return any Metadata. So it's hard for them to implement proper tests since they don't know where the data has been put. 

So or we return the Metadata after each upload. Or we add a command that return the Metadata for a certain key. The output should be something easily parsable to make their life easier

**Comment by islamTaha12** [comment]
closed
```bash
➜  zerostorcli git:(master) ✗ zerostorcli file metadata config.yaml | json_pp
{
   "previous" : null,
   "key" : "Y29uZmlnLnlhbWw=",
   "epoch" : 1504783444508130741,
   "next" : null,
   "encryption_key" : "YWIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=",
   "chunks" : [
      {
         "key" : "DSEAjJd6uLyX4gnVTxm2vGLLSoWopjZvEo//IzPCWC4=",
         "shards" : [
            "http://10.147.17.205:8080",
            "http://10.147.17.66:8080",
            "http://10.147.17.234:8080",
            "http://10.147.17.85:8080"
         ],
         "size" : 783
      }
   ],
   "configPtr" : null
}

```
