### ISSUE TITLE
Add delete object method on client

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#196]
Currently the client can only Read and Write the 0-stor. We should also expose the possibility to delete object

**Comment by iwanbk** [comment]
How is the relation of `delete` operation with reference list?:
- delete API also accept reference list as argument
- client get reference list
- client update reference list
- if it is last reference list, client delete the object

**Comment by zaibon** [comment]
No, delete is a real delete and is not related with reference list. Everything is let to the appreciation of the client and how he wants to implement he's own flow. 
Delete should actually delete the files on a 0-stor.

**Comment by GlenDC** [comment]
@zaibon why is this issue marked as `state_verification`?

**Comment by zaibon** [comment]
This is that label set when issue is ready for QA to validate

**Comment by GlenDC** [comment]
I know what the label means. But I dn't see a fix referenced. And neither do I see Q&A verifying and closing it, even though it is like this for 2 months already....

**Comment by GlenDC** [comment]
This has been fixed a while now, and in master the client can Delete an object.
