### ISSUE TITLE
Add UpdateReferenceList method on the client

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#197]
This method is already implemented on the rest and grpc client. But no expose on the high level client.

**Comment by iwanbk** [comment]
How is the flow then to store the data?:
- Write the data
- Update reference list

Don't you think we also need to update reference list on Write?

**Comment by zaibon** [comment]
that's not something we have to integrate into the normal flow.
Reference list is just a feature given by the 0-stor but it's the responsibility of the client to implement it as he wants. So we should just have a method on the client that allows it. Nothing more

**Comment by iwanbk** [comment]
> This method is already implemented on the rest and grpc client

How about add an option to append/remove a reference ID?
Client user could save a round trip in this case.

**Comment by zaibon** [comment]
Yesterday I actually noticed that I forgot to allow to pass the referenceList in the Write method.
It's indeed where it should be, as well as an new method that only update the  referenceList.

How do you think we should proceed. Cause adding this argument to the write method will change the interface. We can add a vatiadic argument so code using the client will still work.

**Comment by iwanbk** [comment]
> Yesterday I actually noticed that I forgot to allow to pass the referenceList in the Write method.

Actually i already sent a PR for this at #234

> We can add a vatiadic argument so code using the client will still work.

Oh, never thought that we already need to keep API stability.
Yeah, i think variadic argument will work.

> How about add an option to append/remove a reference ID?

It is still needed to provide a kind of deduplication.

**Comment by zaibon** [comment]
> Actually i already sent a PR for this at #234

Saw it and added comments on it already.

> Oh, never thought that we already need to keep API stability.

We can probably still get away with a breaking change now.

> How about add an option to append/remove a reference ID?

So you want a method to apprend/remove instead of a set that replace the complete list?

**Comment by iwanbk** [comment]
> So you want a method to apprend/remove instead of a set that replace the complete list?

Yes.

**Comment by zaibon** [comment]
> So you want a method to apprend/remove instead of a set that replace the complete list?
Yes.

Ok that can be added too, What interface do you propose ?

**Comment by iwanbk** [comment]
> Ok that can be added too, What interface do you propose ?


```
POST /object/{id}/reflist
SetReferenceList(key []byte, refList []string)
```
```
PUT /object/{id}/reflist
AppendReferenceList(key []byte, refList []string)
```

```
DELETE /object/{id}/reflist
RemoveReferenceList(key []byte, refList []string)
```

Not sure the endpoint in grpc.
I think we can use an operation type as flag:
- set
- append
- remove

**Comment by zaibon** [comment]
On the rest server we already have `PUT /object/{id}/reflist` to update a reference list
Also REST is going to be dropped in this milestone, no point designing around it.

Regarding the client API, I would return error in each method. The rest LGTM
```go
// SetReferenceList replace the complete reference list for the object pointed by key
SetReferenceList(key []byte, refList []string) error
// AppendReferenceList adds some reference to the reference list of the object pointed by key
AppendReferenceList(key []byte, refList []string) error
// RemoveReferenceList remvoes some reference from the reference list of the object pointed by key
RemoveReferenceList(key []byte, refList []string) error
```

**Comment by iwanbk** [comment]
@zaibon what to do when the reference list size exceed 160?
can't find it in the spec

**Comment by zaibon** [comment]
We should add a test and raise if the size of one of the item is bigger then 160. Cause server size it will be trimed to 160 bytes max

**Comment by iwanbk** [comment]
>  raise if the size of one of the item is bigger then 160

Hmm..not sure what you mean.

From the code, https://github.com/zero-os/0-stor/blob/master/server/db/object.go#L13-L14: 
- max length of reference ID is 16 : i'm sure we need to return error if it > 16
- max number of reference ID is 160 : This is where i'm not sure. I think we have some design somewhere (i think in nbdserver, not sure),  if reference list become > 10, then it will never be deleted.
It seems this is not the case. If it reach > 160, then we simply return error, right?

**Comment by zaibon** [comment]
Yep sorry I miss read, I though you were talking about the 16bytes of the reference length. 
For this, we need to add a check and raise an error if reference is bigger then 16bytes.

Regarding the 160, I think the idea is to prevent to be able to have an object with an infinite number of reference. 
This has nothing to do with the 10 reference of the nbdserver. A least the 160 number doesn't come from there. KDS made some calculation and estimate that 160*16 was reasonable.
