### ISSUE TITLE
Removes python, js, and other non Go files from vendor dir

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#203]
examples:
- vendor/github.com/itsyouonline/identityserver/clients/python 
- vendor/github.com/itsyouonline/identityserver/docs/examples/python/
- vendor/github.com/itsyouonline/identityserver/siteservice/website/

**Comment by GlenDC** [comment]
What you are looking for is `dep prune`, which removes all non-go files, unused files and test files. They are planning to deprecate that command as soon as its integrated in the `dep ensure` command, but for now it's still separately.

Meaning that until `dep prune` is part of `dep ensure`, you'll have to run it separately yourself. Didn't know this myself, but just did it myself for https://github.com/zero-os/0-Disk/pull/450.
