### ISSUE TITLE
zerostorecli produces grpc timeout error however the protocol is rest

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#206]
There are two servers using REST protocol and the config file uses the RET protocol too.

![image](https://user-images.githubusercontent.com/17981089/29775958-60472584-8c07-11e7-8ce0-08879f9cc862.png)

**Actual result**
```bash
failed to create client: grpc: timed out when dialing
```

**Comment by zaibon** [comment]
This is most probably coming from the etcd client which use grpc. Can you ensure your etcd server is running and recheable

**Comment by islamTaha12** [comment]
@zaibon Ya it was running but i found that the running server ips were wrong in the config.
