### ISSUE TITLE
0-stor: check list of consumers is properly populated

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-stor#23]
- spec was not ok, it was mentioned reference counter, needs to be full list
- the counter is required to quickly decide if the data is permanent or not and how many people have referenced this data

**Comment by zaibon** [comment]
Code need to be updated indeed. I don't think we keep full list now.

**Comment by zaibon** [comment]
duplicate of https://github.com/zero-os/0-stor/issues/25
