### ISSUE TITLE
make isn't not working with master

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#238]
I can do 'make' in alpha-8 branch while it throws an error with master

![image](https://user-images.githubusercontent.com/17981089/30434489-beaa4300-9967-11e7-856b-efebb8416d56.png)

**Comment by zaibon** [comment]
https://github.com/zero-os/0-stor/commit/e6f1a976c2ef9e275d3f85b99d701178d5f4decf

**Comment by islamTaha12** [comment]
tested
