### ISSUE TITLE
goroutine leak in client replicateRead

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#240]
`replicateRead` https://github.com/zero-os/0-stor/blob/69565d52f2b4ea4673a9484d1383350144a0fe6f/client/client.go#L441-L492 has goroutine leaks bug.

it is because of this part of code
```go
			select {
			case <-cQuit:
				return
			default:
				obj, err := cl.ObjectGet(key)
				if err != nil {
					log.Warningf("replication read, error reading from %s: %v", shard, err)
					return
				}
				cVal <- obj
			}
```
The `select` supposed to return in case of `cQuit` being closed, but this won't happen in case of it already in `cl.ObjectGet`

Check it [in playground](https://play.golang.org/p/ttI6T25T__) to see it. I simulate `cl.ObjectGet` with `time.Sleep`
I don't send PR to fix it because it seems you don't really want for all servers being hit by the client.
The solutions i can see is either doing it sequentially or concurrently to all servers.

I prefer concurrently, for speed reason.

I could send a PR if you agree @zaibon

**Comment by zaibon** [comment]
This is right. I wanted to avoid we do a call to the store if another one already answered, but my code is buggy indeed.
We should do the `ObjectGet` call before the select.
