### ISSUE TITLE
0-stor: make sure spec has been followed

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-stor#25]
- users are 16 bytes (no meaning for 0-stor)
  - the counter is required to quickly decide if the data is permanent or not and how many people have referenced this data
- We cannot overwrite data !!! once written it can only be deleted, once deleted a new one can be created.

**Comment by zaibon** [comment]
Since we use hash as key, it data overwrite is not possible. If 2 or more user try to set on an existing data, we just update the reference list/counter

**Comment by despiegk** [comment]
we can overwrite

**Comment by Hamdy** [comment]
if user tries to set a file with a key that previously existed, we check crc for old file and new one
if match we increment reference.
If not, we return 409 conflict

**Comment by despiegk** [comment]
- this is wrong behaviour.
- see top remark: user does not has meaning for our system.
- we only keep references
- we don't overwrite data
- the key has no meaning for us !!!!!! this is defined by the person who uses the system, so we cannot consider this to be a hash or anything, we don't know

**Comment by iwanbk** [comment]
> closed this in 1e24407 

Accidentally closed by commit message from client code that  just moved from 0-stor-lib repo
