### ISSUE TITLE
race condition in badger

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#250]
Got race condition during `test -race`
- while working on #248 https://gist.github.com/iwanbk/5ce035d7d8e124d2c2c78d8479526bcb#file-gistfile1-txt

- in 0-disk travis test https://travis-ci.org/zero-os/0-Disk/jobs/278479303
   https://gist.github.com/iwanbk/5ce035d7d8e124d2c2c78d8479526bcb#file-in_0_disk_test-log

**Comment by iwanbk** [comment]
> while working on #248 https://gist.github.com/iwanbk/5ce035d7d8e124d2c2c78d8479526bcb#file-gistfile1-txt

While working on it, i saw nothing suspicious in 0-stor server side.
Could you check it @zaibon ?

**Comment by iwanbk** [comment]
> in 0-disk travis test https://travis-ci.org/zero-os/0-Disk/jobs/278479303
> https://gist.github.com/iwanbk/5ce035d7d8e124d2c2c78d8479526bcb#file-in_0_disk_test-log

It happens on this test
https://github.com/zero-os/0-Disk/blob/c1190fd2c2d9d132e831c320afcd1db2480de20d/tlog/copy/copier_test.go#L105-L106

which test this func
https://github.com/zero-os/0-Disk/blob/c1190fd2c2d9d132e831c320afcd1db2480de20d/tlog/copy/copier.go#L101-L140

**Comment by iwanbk** [comment]
i tried to add sync.Mutex to zero-os/0-stor/server/db/badger/badger.go, not as fix attempt, only wanna see how it affect the issue.
We still have race condition :)

**Comment by iwanbk** [comment]
adding `opts.SyncWrites = true` to the test server didn't fix the issue

**Comment by zaibon** [comment]
I should you should report that on badger repo. I don't see anything fishy in our code either.

**Comment by iwanbk** [comment]
An issue filled to badger repo with a way to reproduce it.

After some digging, i found that this issue started at this commit https://github.com/dgraph-io/badger/commit/46ceb47341cea03fd822fb81988baedacdd2f631

Moving back to older commit seems to fix this issue
