### ISSUE TITLE
KeyExists method  0-stor client

### ISSUE THREAD

**Issue by chrisvdg** [zero-os/0-stor#255]
To implement the `EXISTS` command for Zedis a method is needed for the 0-stor client to  check if a key exists on the 0-stor as there is currently no clean way to do this.

**Comment by iwanbk** [comment]
We can use https://godoc.org/github.com/coreos/etcd/client#IsKeyNotFound

**Comment by chrisvdg** [comment]
@iwanbk , is this returned from Client.GetMeta?
I'm also getting errors getting/importing etcd, so going to stay at checking for ErrMetadataNotFound for now

**Comment by iwanbk** [comment]
> @iwanbk , is this returned from Client.GetMeta?

No.

I think that func need to be fixed to use https://godoc.org/github.com/coreos/etcd/client#IsKeyNotFound instead of using ErrMetadataNotFound.

If you have time, feel free to work on it.

**Comment by iwanbk** [comment]
> I think that func need to be fixed to use https://godoc.org/github.com/coreos/etcd/client#IsKeyNotFound

I just realized that above func only available for client v2.

client v3 has another func, which seems to only useful on transaction
https://godoc.org/github.com/coreos/etcd/clientv3/clientv3util#KeyExists

So, GetMeta might be our best method for now.
