### ISSUE TITLE
Zerostorcli returns an error message in case of it fails in reparring a file

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#261]
**Steps:**
- I have 3 servers
- Upload a file with data=2, parity=1 and distribution size > reptation_size 
- Access those servers and delete all database files.
- Try to repair this file though zerostorcli 

**Actual result**
![image](https://user-images.githubusercontent.com/17981089/31054266-74efe526-a6af-11e7-95eb-9623bb089a9d.png)

**Expected result**
This Error message should be improved. It should throw fail instead of error.

**Version**
7c623ead388511d44dcab7e3891800a42d4e4b7e

**Comment by iwanbk** [comment]
> This Error message should be improved. It should throw fail instead of error.

Go doesn't have `throw fail` mechanism, only returning an error.

We might be able to improve the error message format.
any idea for the better format?

**Comment by zaibon** [comment]
I think what should happens here, is the error message that is printed to the user should be properly formatted, currently we just output the json representation of the error received from the client. But for the final user this is ugly. All the required information for a nicly formatted error message are present. It us just the matter of printing it properly

**Comment by iwanbk** [comment]
I think marshalIndent is enough https://golang.org/pkg/encoding/json/#MarshalIndent, not really pretty as it still in json format, but the original json format will give complete info.
