### ISSUE TITLE
Investigate faster way to update reference list

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#263]
0-stor has shown to be pretty slow when use in the tlog of [0-disk](https://github.com/zero-os/0-disk) project. 

Specially when a the tlog does some operation on the reference list of some objects.
The problem is the in 0-stor, the object and its reference list are serialized together into a binary blob before being written on disk. This design force to read/write the full data back every time we want to update the reference list.

I made some benchmark and it shows that the write speed is proportional with the size of the data of the object. And this even if we only change the reference list of the object. 
Code can be found at : https://github.com/zero-os/0-stor/blob/perfs/server/db/bench_test.go#L27

```
BenchmarkSetReferenceList/with_data,_size:1024-4                  100000             20399 ns/op
BenchmarkSetReferenceList/with_data,_size:4096-4                  100000             22313 ns/op
BenchmarkSetReferenceList/with_data,_size:10240-4                  50000             25339 ns/op
BenchmarkSetReferenceList/with_data,_size:1048576-4                 2000            944696 ns/op
```

After this I created a Decode function that allow to only load the reference list and not the full data object. And then run the same test. With this method, updating a reference list is a constant time operation that is not bound to the size of the data.
```
BenchmarkSetReferenceList/without_data,_size:1024-4                50000             37829 ns/op
BenchmarkSetReferenceList/without_data,_size:4096-4                50000             37931 ns/op
BenchmarkSetReferenceList/without_data,_size:10240-4               50000             37940 ns/op
BenchmarkSetReferenceList/without_data,_size:1048576-4             50000             41007 ns/op
```

I then started to think of a way to update our code to meet this performance.
My first thought was to update the object struct to use method to access it's content instead of attribute. Like this we could serialize only the part of the data needed when needed. 
The problem with this is that after updating the reference list for example, I still need to have the rest of the data loaded before being able to rewrite the full binary blob on disk.

My second though is to change how we serialize object on disk and keep the data and the reference list on two separate blob that can be queried and updated alone. The logic of dealing with this would be hidden by the object stuct and the upper layer could just get the piece of data its need when needed.

**Comment by zaibon** [comment]
Some first draft of this solution has been implemented on https://github.com/zero-os/0-stor/tree/perfs

I'm not totally happy with the new API of the Object struct cause now it needs a DB object which break a bit the isolation of the type from the db package.

**Comment by iwanbk** [comment]
> My first thought was to update the object struct to use method to access it's content instead of attribute. Like this we could serialize only the part of the data needed when needed.
> The problem with this is that after updating the reference list for example, I still need to have the rest of the data loaded before being able to rewrite the full binary blob on disk.

Not sure what you mean here.
If it means when updating ref list we need to do these:
- get ref list
- update ref list
- get rest of the data
- update full data

then it seems we might have consistency issue if the overall transaction failed.

> My second though is to change how we serialize object on disk and keep the data and the reference list on two separate blob that can be queried and updated alone. The logic of dealing with this would be hidden by the object stuct and the upper layer could just get the piece of data its need when needed.

Sounds like a better solution and it seems you already implemented it on "perfs" branch.

As a side note, we might have race bug related to this operation. I created a separate issue #264 because it is not specific to ref list
