### ISSUE TITLE
new method to allow new consumer to (de)register as user to the data

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-stor#27]
- to add consumer to consumer list
- also remove

use case
- allow multiple consumers to allocate same data

**Comment by zaibon** [comment]
I don't think we need an explicit method to do that,
Set and Delete should do that by default.

User set new data => save data
If a user try to set and existing data => update reference list, so multiple consumer for the same data
If user delete data that has reference counter > 1, decrease reference counter
If user delete data that has reference counter == 1, mark as deletable

**Comment by zaibon** [comment]
Flow has been changed. reference list is now exposed to the client
