### ISSUE TITLE
badger Delete might be too heavy

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#274]
During my work for https://github.com/zero-os/0-Disk/issues/281 (deleting tlog data)  on 0-Disk's `delete-tlog` branch (https://github.com/zero-os/0-Disk/tree/delete-tlog), the provided test failed on travis without clear error message.

Because profiling didn't give me enough result on succeeded test (mem usage only 99MB).
(succeeded test was created by reducing number of data). I tried to disable code that i guess too heavy for the CPU or memory.
And then i found that my test would succeeded if i disable the code to delete the object from 0-stor's badger.

https://github.com/zero-os/0-stor/blob/f0fd376ae5506eaf1dae514497e5ec56e9db4d38/server/db/badger/badger.go#L54-L60

It is very surprising for me.
I can only guess that badger's `Delete` do a really heavy work.

**Comment by iwanbk** [comment]
> And then i found that my test would succeeded if i disable the code to delete the object from 0-stor's badger.

I reproduced the failed test on small VM with only 2GB of memory.
And then disabling badger Delete succeeded on this VM

**Comment by chrisvdg** [comment]
Could this be an issue with the Go race detector? When running the test with the race flag my ram consumption peaked with 4.81Gb over normal usage, without it only peaked at 0.65Gb over normal.

**Comment by zaibon** [comment]
Seems to be the reason indeed. @chrisvdg  can you check the test and reduce the amount of memory we allocate during this test and see if it fixes it?

**Comment by chrisvdg** [comment]
@zaibon , reduced the  constants that are used to set up the resources for the test by half and the delete-tlog branch passes now

**Comment by iwanbk** [comment]
> @zaibon , reduced the constants that are used to set up the resources for the test by half and the delete-tlog branch passes now

I actually already did the same thing, but still not sure that it is not the right way to make the test passed.
i'm afraid that it means our tlog deletion will fail when we have a lot of transactions

**Comment by zaibon** [comment]
@iwanbk can you write some tests with your tlog client to see how it behave with a lot of data.
I don't think the load go runtime has during a test with race detector enabled can be compared with real production scenarios. But better safe then sorry.

**Comment by iwanbk** [comment]
> Edit:
> Still seems to be within typical overhead for race detection (https://golang.org/doc/articles/race_detector.html#Runtime_Overheads)
> Maybe we need to look into reducing memory usage for the test?

Ah yeah, missed this point,  it seems to be the real issue then.
