### ISSUE TITLE
Tune GOMAXPROCS value to get most performance

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#282]
From the badger README:
> Are there any Go specific settings that I should use?

We highly recommend setting a high number for GOMAXPROCS, which allows Go to observe the full IOPS throughput provided by modern SSDs. In Dgraph, we have set it to 128. For more details, see this thread.

We should benchmarck 0-stor with different values of GOMAXPROCS and determine what works best for us

**Comment by katia-e** [comment]
I tested performance by uploading sequentially uploading 100 byte slices of 200 bytes each to 4 nodes.
Table bellow shows speed and time for the upload for different values of GOMAXPROCS. To average processing time the upload was repeated 100 times for each value of GOMAXPROCS

 22783 byte/s  |  0.89 sec |   GOMAXPROCS = 1
 25620 byte/s  | 0.79 sec  |   GOMAXPROCS = 4
 25216 byte/s  | 0.80 sec  |   GOMAXPROCS = 8
 26279 byte/s  | 0.77 sec  |   GOMAXPROCS = 32
 26388 byte/s  | 0.77 sec  |   GOMAXPROCS = 64
 25610 byte/s  | 0.79 sec  |   GOMAXPROCS = 128
 25718 byte/s  | 0.79 sec  |   GOMAXPROCS = 256
 24771 byte/s  | 0.83 sec  |   GOMAXPROCS = 512
 21946 byte/s  | 0.93 sec  |   GOMAXPROCS = 1000
 21811  byte/s | 0.93 sec  |   GOMAXPROCS = 1024

## Conclusion
- For different values of GOMAXPROCS uploading process performs differently, however, the difference is not significant
- The best performance is observed for GOMAXPROCS = 64.
- The result varies depending on number of slices and slice sizes.

**Comment by GlenDC** [comment]
Fairly sure that this will also heavily depend on the hardware used, and especially how many CPU cores one has available. So not sure you can/should just set a constant GOMAXPROCS value.

**Comment by zaibon** [comment]
> So not sure you can/should just set a constant GOMAXPROCS value.

This idea come from the badger README itself. They notice big performance changes by tuning the value of GOMAXPROCS. So I wanted to test if we could also leverage this. 

That said I know that they get big performance boosts cause they batch their write over a lot of gorountine and have lots of concurrency. We don't really do that in 0-stor so I don't expect too much gain from it.

**Comment by zaibon** [comment]
not relevant since we don't use badger anymore
