### ISSUE TITLE
Prettyfy cli metadata output

### ISSUE THREAD

**Issue by chrisvdg** [zero-os/0-stor#286]
The current output of the  `file metadata` command currently looks as follows
![screenshot from 2017-11-06 15-40-19](https://user-images.githubusercontent.com/23582741/32446444-37dec514-c309-11e7-9653-8040c0b500c6.png)

It doesn't look very readable nor clean.
This could at the very least be turned into prettified JSON.

**Comment by zaibon** [comment]
Agree, but then we should also add a flag that output pure json so the output can be easily parsed by a machine.

**Comment by GlenDC** [comment]
I would recommend that by default it outputs as it does right here, and only when you specify a flag explicitly (e.g. `--pretty`) that it would output it in prettified JSON. That's also what we do for the `zeroctl describe snapshot` command in the 0-Disk project.

**Comment by zaibon** [comment]
Let's try to be consistent in our CLI so let's follow same behavior as `zeroctl`

**Comment by chrisvdg** [comment]
Should there be an output for "humans" or only output JSON and prettified JSON?
In my branch currently I have a human output without flags, a `json` flag for flat JSON and a `pretty` flag for prettified JSON

**Comment by zaibon** [comment]
> In my branch currently I have a human output without flags, a json flag for flat JSON and a pretty flag for prettified JSON

Keep it like this then.

**Comment by GlenDC** [comment]
But why is the `json` flag required? What do you output if you don't give any of these flags?

**Comment by zaibon** [comment]
@GlenDC see https://user-images.githubusercontent.com/23582741/32501242-cc9239b0-c3d7-11e7-92af-35c02c24da01.png

**Comment by GlenDC** [comment]
Oh I see. Is it required that we output both YAML and JSON?
