### ISSUE TITLE
0-stor: also implement grpc interface

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-stor#29]
- do rest & grpc
- should be able to do in same daemon
- will give more performance
- our std client should use grpc

**Comment by zaibon** [comment]
Why gRPC ? shouldn't we stick with capnp since we use this format everywhere else ?
I don't know if the perfomance of gRPC and capnp rpc are comparable though.

**Comment by despiegk** [comment]
we decided to go grpc because better supported

**Comment by zaibon** [comment]
protocol buffer and grpc specs have been written and code generated on branch [grpc](https://github.com/zero-os/0-stor/tree/grpc)

I also create some scaffolding for the gprc server.
Before continuing I think we should solve https://github.com/zero-os/0-stor/issues/31

**Comment by zaibon** [comment]
Server side implementation is done (https://github.com/zero-os/0-stor/pull/106)
This implementation doesn't have support for jwt yet. 
I'll work on that in my next PR

**Comment by zaibon** [comment]
PR regarding jwt : https://github.com/zero-os/0-stor/pull/137
