### ISSUE TITLE
Replace blak2b hash with something more suited for our need

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#297]

**Comment by GlenDC** [comment]
@maxux can you report your progress here? I noticed in the meeting of yesterday morning that you seemed to have made progress, yet I don't see it here. Please make sure to always keep your progress tracked in GitHub.

**Comment by maxux** [comment]
There are no specific progress yet, we just replaced blake2 with sha1 and performance was quite double. I'll post report when I'll have proper results :)

**Comment by GlenDC** [comment]
@maxux can you check out the benchmarks available in the https://github.com/zero-os/0-stor/tree/master/client/pipeline/crypto package? On my machine blake2 seems faster than sha255, so I would love your feedback, so we can decide on a default (currently it is sha256 as agreed with @zaibon, but given my benchmark results it seems blake2 is a better choice).

Information about my machine:

> OS: OSX El Capitan (10.11.6)
> CPU: 2,7 GHz Intel Core i5
> RAM: 8 GB 1867 MHz DDR3
> GPU: Intel Iris Graphics 6100 1536 MB
> Laptop Model: MacBook Pro (Retina, 13-inch, Early 2015)

Here are my results of those benchmarks:

256-bit, without providing an encryption key:

```
BenchmarkSumBlake2b256er_WithoutKey/512-bytes-4         	 2000000	       814 ns/op
BenchmarkSumBlake2b256er_WithoutKey/4096-bytes-4        	  300000	      5018 ns/op
BenchmarkSumBlake2b256er_WithoutKey/131072-bytes-4      	   10000	    154617 ns/op
BenchmarkSumBlake2b256er_WithoutKey/1048576-bytes-4     	   10000	    153958 ns/op

BenchmarkSHA256Hasher_WithoutKey/512-bytes-4            	 1000000	      2028 ns/op
BenchmarkSHA256Hasher_WithoutKey/4096-bytes-4           	  100000	     13057 ns/op
BenchmarkSHA256Hasher_WithoutKey/131072-bytes-4         	    3000	    415597 ns/op
BenchmarkSHA256Hasher_WithoutKey/1048576-bytes-4        	     500	   3483513 ns/op
```

256-bit, while providing a key:

```
BenchmarkSumBlake2b256er_WithKey/512-bytes-4            	 1000000	      1019 ns/op
BenchmarkSumBlake2b256er_WithKey/4096-bytes-4           	  300000	      5242 ns/op
BenchmarkSumBlake2b256er_WithKey/131072-bytes-4         	   10000	    153059 ns/op
BenchmarkSumBlake2b256er_WithKey/1048576-bytes-4        	    1000	   1217927 ns/op

BenchmarkSHA256Hasher_WithKey/512-bytes-4               	  500000	      2974 ns/op
BenchmarkSHA256Hasher_WithKey/4096-bytes-4              	  100000	     14587 ns/op
BenchmarkSHA256Hasher_WithKey/131072-bytes-4            	    3000	    433061 ns/op
BenchmarkSHA256Hasher_WithKey/1048576-bytes-4           	     500	   3417041 ns/op
```

512-bit, without providing an encryption key:

```
BenchmarkSumBlake2b512er_WithoutKey/512-bytes-4         	 2000000	       836 ns/op
BenchmarkSumBlake2b512er_WithoutKey/4096-bytes-4        	  300000	      5068 ns/op
BenchmarkSumBlake2b512er_WithoutKey/131072-bytes-4      	   10000	    153850 ns/op
BenchmarkSumBlake2b512er_WithoutKey/1048576-bytes-4     	    1000	   1217831 ns/op

BenchmarkSHA512Hasher_WithoutKey/512-bytes-4            	 1000000	      1704 ns/op
BenchmarkSHA512Hasher_WithoutKey/4096-bytes-4           	  200000	      9830 ns/op
BenchmarkSHA512Hasher_WithoutKey/131072-bytes-4         	    5000	    291087 ns/op
BenchmarkSHA512Hasher_WithoutKey/1048576-bytes-4        	    1000	   2254017 ns/op
```

512-bit, while providing a key:

```
BenchmarkSumBlake2b512er_WithKey/512-bytes-4            	 1000000	      1043 ns/op
BenchmarkSumBlake2b512er_WithKey/4096-bytes-4           	  300000	      5234 ns/op
BenchmarkSumBlake2b512er_WithKey/131072-bytes-4         	   10000	    154824 ns/op
BenchmarkSumBlake2b512er_WithKey/1048576-bytes-4        	    1000	   1218843 ns/op

BenchmarkSHA512Hasher_WithKey/512-bytes-4               	  500000	      2787 ns/op
BenchmarkSHA512Hasher_WithKey/4096-bytes-4              	  200000	     10998 ns/op
BenchmarkSHA512Hasher_WithKey/131072-bytes-4            	    5000	    298037 ns/op
BenchmarkSHA512Hasher_WithKey/1048576-bytes-4           	     500	   2381294 ns/op
```

As you can see, in all my benchmarks, blake2b seems to perform better than SHA, for the same bit-size. So that makes me think we should still use blake2b as a default, rather than SHA.

CC @zaibon

**Comment by GlenDC** [comment]
For now it seems blake2b is a better option than SHA, so we'll go for that one as the default. If we find another option in the near future, we can always implement it and turn it into the default hasher, it's not that much of a trouble, and as long as people don't abuse the API, it shouldn't have to break their code at all.
