### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by chrisvdg** [zero-os/0-stor#298]
- [ ] Add/update benchmarks on package level to keep track of performance
- [ ] Make them part of the `makefile` like in 0-Disk

**Comment by zaibon** [comment]
This should be handle as part of  #296 . But indeed having some benchmark that can ben trigger from the performance testing is a good idea.

**Comment by GlenDC** [comment]
How is this issue and issue #296 going, @chrisvdg?

+ We need proper performance tests/benchmarks to ensure that the ztordb is performance enough. This can be done using golang Benchmarks;
+ Further it might be nice to also have a simple Go project available which can work with any amount of 0-stor servers (with or without a metadata db), which will touch the entire API surface to test the performance of all the different elements;

Right now however I would suggest to focus on the redesign of the 0-stor client/server, as a lot of that will chance the results a lot, as well as the APIs of the codebase.

**Comment by chrisvdg** [comment]
@GlenDC I wanted to start on this after the middleware issues but in a scrum meeting @zaibon already suggested to focus on the redesign for now, so will hold of to start on these benchmarking issues.

**Comment by zaibon** [comment]
duplicate of #296
