### ISSUE TITLE
unnecessary slice allocations and copies in BadgerDB

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#300]
In BadgerDB we find several locations where we copy slices which we've just fetched (and uniquely allocated for this operation), right before we return:

+ https://github.com/zero-os/0-stor/blob/ff36fa680b914bcc28f0fb3a56a84a4f0494984a/server/db/badger/badger.go#L109-L110 (can be replaced with `val = v`);
+ https://github.com/zero-os/0-stor/blob/ff36fa680b914bcc28f0fb3a56a84a4f0494984a/server/db/badger/badger.go#L162-L164 (can be replaced with `result = append(result, b)`);
+ https://github.com/zero-os/0-stor/blob/ff36fa680b914bcc28f0fb3a56a84a4f0494984a/server/db/badger/badger.go#L190-L193 (can be replaced with `result = append(result, key)`);

I checked the Godocs for badger, and I don't seem to say anywhere that you need to copy those values before usage. That wouldn't make sense either, as there would be no safe way to guarantee that you copy the value on time in an async environment.

Just to be sure however, I checked the badger code, and it seems to create those items on the fly, and uniquely per operation. As far as I can see, the key and value slices are already unique to that item, and can be safely propagated to the BadgerDB user.

**Comment by zaibon** [comment]
https://godoc.org/github.com/dgraph-io/badger#Item.Value

> The returned value is only valid as long as item is valid, or transaction is valid. So, if you need to use it outside, please parse or copy

**Comment by GlenDC** [comment]
Fair enough, I see that https://godoc.org/github.com/dgraph-io/badger#Item.Key mentions the same thing. Somehow I read over that.
