### ISSUE TITLE
fix all warnings and formatting in (golang) codebase

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#303]
Warnings should be treated as errors, and be fixed. Using the Golang toolchain you can easily check for and list warnings if they exist:

```
go vet $(go list ./... | grep -v vendor)
```

You can format all code at once using:

```
go fmt $(go list ./... | grep -v vendor)
```

For now it seems however that all formatting is fine as it is on the master branch.

Note that you should install, configure and use Golang plugins in your favorite editor/IDE, such that the warnings are automatically listed and formatting is automatically corrected when saving a file.

Once all warnings have been fixed (in a reasonable way), also ensure to add the following to our `.travis.yml` file, such that we also have a Travis CI test that ensures all checked in code is warning free and correctly formatted:

```diff
diff --git a/.travis.yml b/.travis.yml
index fcd3a6b..6d51112 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -25,6 +25,13 @@ matrix:
       script: make
 
     - language: go
+      go: 1.9
+      install: skip
+      script:
+        - go vet $(go list ./... | grep -v vendor)
+        - diff -u <(echo -n) <(gofmt -d $(find . -name "*\.go" | grep -v '\.git/' | grep -v vendor))
+
+    - language: go
       sudo: true
       dist: trusty
       go: 1.9
```

**Comment by GlenDC** [comment]
This has today also been fixed in 0-Disk: https://github.com/zero-os/0-Disk/pull/619

**Comment by zaibon** [comment]
Nice trick to have in travis, I like it

**Comment by katia-e** [comment]
1. Running ```go vet $(go list ./... | grep -v vendor)``` returns several errors like
```client/lib/shard_error.go:62: Nil passes lock by value: lib.ShardError contains sync.Mutex```

The reason is that we pass copy of the lock to the function, as ShardError is defined as follows
```
type ShardError struct {
	errors []serverError
	mux    sync.Mutex
}
```

and function is called as follows
``` 
func (se ShardError) Nil()
```

What is the best way to resolve it?
- redefine mux in ShardError type  as 

```
mux    *sync.Mutex
```
- or pass a pointer to the function
``` func (se *ShardError) Nil()```

2. I didn't find any test available for package lib (client/lib/shard_error.go). Shall I make one?

**Comment by GlenDC** [comment]
> func (se *ShardError) Nil()

This is defintely the way to go imho.

I would always pass complex structures by pointer for all its methods. And a structures which encapsulates a mutex lock falls definitely under complex structure. Shouldn't be just that method though, will have to be all its methods.

That's really a bad bug. I wonder how that ever got to master, shouldn't have happened.

> I didn't find any test available for package lib (client/lib/shard_error.go). Shall I make one?

If you encounter code that doesn't have unit tests, and you think it should really have one or multiple unit tests, than feel free to add them yes. But perhaps make another issue for that, so you can first focus on the issue at hand.

In the case of shard_error, I do think it definitely deserves a couple of tests:

+ One simple test to ensure that `Nil`/`Num`/`String` works in all scenarios (no error, one error, multiple errors). These can all be tested in one single unit test function. for `String` you shouldn't compare an exact string, instead just ensuring it's empty when it should be empty and it's not empty when it's not, should be fine enough for that method;
+ One test to ensure that ShardError is indeed thread-safe;

But like I said, create a separate issue for this, and focus now first on fixing all the warnings.

**Comment by katia-e** [comment]
Will do. 
Additionally, in the same shard_error.go my Golang plugin gives on 
``` func (se *ShardError) Errors() []serverError  ```

warning
```
exported method Errors returns unexported type []lib.serverError, which can be annoying to use
type serverError struct 
```
should it be done differently in this case?

**Comment by GlenDC** [comment]
Yeah that's another bad warning. I seriously don't understand how this code got to master. Either way, in general we have several options to resolve a situation such as this:

+ Keep the underlying type hidden, and return it as an interface (which would be in this case the `error` interface;
+ Make the type public and keep returning it;

In most cases you should go for the second option. As a general rule of thumb is to return stuff by their actual type and use them as interface when required.

+ On top of making that serverError a public type,
+ I would also make it implement the `error` interface
  + which you can do by providing the `func (se *ServerError) Error() string` method
   + you can mov/borrow most of the logic defined in
      `formatPrettyError` and `formatServerList` for this;

**Comment by zaibon** [comment]
I would really prefer we  re-implement this shard error altogether. I know this piece of code bother me for some time. Maybe using the https://godoc.org/golang.org/x/sync/error oups package.

**Comment by GlenDC** [comment]
Oh. I guess I should have checked where it's used. Either way that would be for a different issue though. This issue is just about fixing all warnings, so we can start from a clean sheet. Feel free to open an issue for it though @zaibon if you have some good directions to give it could be another mentor issue.
