### ISSUE TITLE
cached data and checksum not reset in (*db.Object).Delete

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#308]
When calling the `(*db.Object).Delete` method, we delete the data (and thus also checksum) from the database, but we do not reset the checksum and data cached in the in-memory object model. We should probably do something such as `o.data, o.crc = nil, 0`, such that next time when we call either `Data()` or `CRC()`, we get the correct behavior. 

Source: https://github.com/zero-os/0-stor/blob/2ecaea6aadbf096a3325143fd768621719e38d75/server/db/object.go#L268-L274

**Comment by GlenDC** [comment]
@zaibon please verify if this bug report is valid.

**Comment by zaibon** [comment]
@glendc yep this bug is valid and your solution too.

**Comment by GlenDC** [comment]
No longer needed, and superseded by #320.
