### ISSUE TITLE
create JWT Verifier object and avoid globals in jwt package

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#310]
Right now we have one global (private) key, `iyoPublicKeyStr`. Than we provide some method (`SetJWTPublicKey`) to override that Key (in a totally unsafe) way (which is only ever used for testing purposes. On top of that we use that jwt package only ever in one place, and that is in the `server/jwt.go` file, where we define the real interface for our real jwt server desires. In this `server/jwt.go` file we also have some more globals (e.g. `authEnabled`, which we use only for some test/dev purposes).

First of all these globals really smell, and in this case they are very easily avoidable by encapsulating them in a struct, and attach the methods to that struct. On top of that it seems very silly to provide a `jwt` package, but than define a lot of the business logic and API we really care about as a separate file outside the package and semi-private.

I propose that we move all `jwt`-related  business logic, variables (includes that global cache), constants and types to the `server/jwt` package. Than we'll define the following struct:

```go
var (
   defVerifier *Verifier
   createDefVerifierOnce sync.Once
)

func DefaultVerifier() *Verifier {
   createDefVerifierOnce.Do(func() {
      var err error
      defVerifier, err = NewVerifier(iyoPublicKeyStr, true)
      if err != nil {
         panic(err)
      }
   })

   return defVerifier
}

// create a new Verifier
func NewVerifier(pubKey string, authEnabled bool) (*Verifier, error) {}

type Verifier struct {
    key crypto.PublicKey
    authEnabled bool
    cache *ccache.Cache
}

func (v *Verifier) CheckPermissions(expectedScopes, userScopes []string) bool {}
func (v *Verifier) ValidateNamespaceLabel(nsid string) error {}
func (v *Verifier) CheckJWTGetScopes(tokenStr string) ([]string, int64, error) {}

func (v *Verifier) ValidateJWT(ctx context.Context, method Method, label string) error {}
func (v *Verifier) GetScopes(token string) ([]string, error) {}
func (v *Verifier) ExtractJWTToken(ctx context.Context) (string, error) {}
func (v *Verifier) ExpectedScopes(method Method, label string) ([]string, error) {}
```

In short, there should be no more `server/jwt.go` file after this issue has been resolved, and all logic, state and types jwt-related should be defined in the `server/jwt` package. This will help us avoid the globals. This struct will have to be created where we currently use the private functions which are right now defined in `server/jwt.go` file (e.g. vaidateJWT, used in the namespace and object API).

Perhaps the first 3 `Verifier` methods aren't needed, but I left them in for now, for the sake of completion. They are public now as well.

By forcing the users of these jwt methods (e.g. Namespace-/Object- API), we also allow for testing purposes to replace the JWT calls with our test verifier, without the need on any global state for this. Global state should be avoided in most cases, especially if we only do _only_ because of some test code.

**Comment by zaibon** [comment]
On top of that I would like to also change how we actually use the verifier. 
Currently in all protected grpc handler we have something like:
https://github.com/zero-os/0-stor/blob/0b38327dabe35ee8a08dffed117fb035b336b0b9/server/object_api.go#L32-L34

This can be achieve using grpc middleware. I only discover about it recently. That will allow us to keep logic separated and in a single place.

Some pointer about grpc middleware :
- https://github.com/grpc-ecosystem/go-grpc-middleware
- https://github.com/grpc/grpc-go/blob/master/interceptor.go

**Comment by GlenDC** [comment]
> On top of that I would like to also change how we actually use the verifier.

Sure but that would be a different issue.

The jwt package shouldn't have to know anything about GRPC. So this middleware can be written in the server GRPC code using the jwt pakage and verifier we provide here.

**Comment by zaibon** [comment]
> The jwt package shouldn't have to know anything about GRPC. So this middleware can be written in the server GRPC code using the jwt pakage and verifier we provide here.

That's how I see it too

**Comment by GlenDC** [comment]
Great, I created a separate issue (see issue #317), that can be done after this issue has been resolved. Let's keep these mentor issues as small as possible.
