### ISSUE TITLE
proposal: remove 0-stor server

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#312]
I propose to remove the 0-stor server.

90% of the work is already done in the client. I'm talking about compression, encryption, chunking, erasure coding and perhaps even some more stuff.

On top of that we're also planning to provide a daemon that will run the client for you in the background (see #68). That basically turns the client into a server.

The server does really not do much at all. The only thing it does is checksum, store and fetch data. On top of that it also stores and fetches reference list. Really that is not a lot at all. It also provides permission checking using IYO JWT, but that is also almost nothing of code. To me it seems a waste of resources to provide an entirely separate server for this, while the client is already doing so much processing anyhow, it can just as well do the final part of the road and store it in the database.

So I propose we provide a nice 0-stor API (merging the client and server code into one). And on top of that provide a command line tool which allows you to run simple commands from the command line (by simply calling that 0-stor API). And lastly provide a daemon server which exposes the API as a GRPC service.

**Comment by GlenDC** [comment]
As our main language language is Golang, I would keep the reference implementation in Golang. 

However it might be interesting to also provide a Rust version. Shouldn't take too long, as 0-stor is relatively simple. Obviously we would first want to prototype to ensure that we indeed get a big performance boost. But if that is the case, it would be nice to provide this alternative Rust version. Because if we're anyway going to rely on a daemon service for clients such as the Python client, than it doesn't really matter any longer if that daemon is written in Rust or Golang. On top of that it gives us the performance that we can get with a language like C, while allowing us to do so in a sane language environment.

**Comment by GlenDC** [comment]
This is just a proposal though, happy and very curious to hear your opinions on this one @zaibon.

**Comment by iwanbk** [comment]
I think i really missed something here.
If we don't have the server, how we store the data on our 0-stor server?

> And lastly provide a daemon server which exposes the API as a GRPC service.

This is exactly what the current server does, no?

**Comment by GlenDC** [comment]
> I think i really missed something here.

Nothing missed, I'm proposing it out of the blue

> If we don't have the server, how we store the data on our 0-stor server?

You wouldn't, you would store it directly in the Database. It's not like we now store something in the 0-stor server, the 0-stor server stores content in the Database as well. Well to be fair you wouldn't store it in the Database yourself, that would happen for you by using the API (client), just as you kinda do now. It's just that we're cutting out another connection (client->server).

> This is exactly what the current server does, no?

Not really. The server exposes its API through the GRPC interface. The daemon exposes the client API through the GRPC interface. (unless I misunderstand something here).

**Comment by GlenDC** [comment]
To recap of what I'm proposing:

+ Merge current 0-stor server and 0-stor client logic as a single 0-stor library;
+ You would use library pretty much the same as the current 0-stor client;
+ The zerostorcli tool can pretty much stay as it is;
+ The daemon project I would just call 0-stor server and it would run the 0-stor library as a GRPC service;
+ This new 0-stor server can also be started as a daemon when run using a specific flag;

**Comment by zaibon** [comment]
Let me first clarify something. The reason we are creating this client daemon is because we don't want to re-implement all the client logic for each language. 

All the logic of the 0-stor indeed is located in the client and this is on purpose. The server is really just an network interface on top of badger so it can be reach from remote.

With your proposal I don't really see how this can be maintain cause the daemon would have the logic and all the heavy work would then be done on server side. Which is not something we want to do. Or did I misunderstood something ?

Regarding rust implementation I wouldn't go there just yet. Maybe once we have a proper performance figure and we know what are the bottleneck maybe rust could be checked to see if it could solve these problem. But for now I don't see this a priority.

**Comment by GlenDC** [comment]
> With your proposal I don't really see how this can be maintain cause the daemon would have the logic and all the heavy work would then be done on server side. Which is not something we want to do. Or did I misunderstood something ?

Yes you misunderstand something here. The daemon would really not be different from what you want it to do now (if different at all). Except that I don't think we have to _call_ it a daemon, and instead can just be a server that optionally runs as a daemon.

The big change is in this proposal is that the work that is now done by the 0-stor server is now also done by the 0-stor client, and we would restructure the code also a bit more in regards of that spirit.

If still not clear, we can discuss it later today over voice.

**Comment by zaibon** [comment]
So we would have only one big binary that contains everything and that can be started in different way. Or to be used as the current server, or to be used as the `client proxy`/daemon for user language to use.

**Comment by GlenDC** [comment]
No.

In my eyes the daemon==server (but you're confused I guess because you keep thinking about what you currently call the 0-stor server, but you should really forgot about that in the context of this proposal, as that no longer exists). It just serves the client from a GRPC interface (or w/e interface you were planning to use).

And the zerostorecli would remain as it is, calling client commands.

**Comment by zaibon** [comment]
Let's add this topic to the meeting of today. Writing doesn't seems to work for this topic ;-)

**Comment by GlenDC** [comment]
This proposal is declined, as there was a misunderstanding on my part, creating a misunderstanding for everybody.

Even though the logic of the 0-stor server is (currently) very simple:

+ We require it as a server as badger does not provide an interface on its own, and thus for each badger DB we require a 0-stor server for us to store and fetch data from an external source (using the client);
+ In the near future the 0-stor server will also get some more responsibility and start handling the reservation of space and physical space management;

Mainly because of the first point there is no point in removing the 0-stor server.

The proposal of having an alternative (second) client written in Rust (with specifically having in mind to run it as a daemon/server), has moved to the investigation issue #316.
