### ISSUE TITLE
client : only creates erasure encoder once

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#313]
We currently create new erasure encoder on each `distributeWrite` call.

https://github.com/zero-os/0-stor/blob/0b38327dabe35ee8a08dffed117fb035b336b0b9/client/client.go#L651-L654

We should be able to create the encoder once, at the client object creation

**Comment by GlenDC** [comment]
Resolved by merging in PR #418 into master (722f6e2f133a42e237b213708649bbe8b0e12446).
