### ISSUE TITLE
decide on command-line tool library/framework

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#318]
Currently we use ~github.com/codegangsta/cli~ https://github.com/urfave/cli as the command-line tool library/framework for all 0-stor binaries. For 0-Disk we use however https://github.com/spf13/cobra.

The goal of this issue is to decide which of those 2 we want to keep using, so we can use the same Command-line tool framework for all 0-stor/0-disk/0-tlog binaries.

**Comment by iwanbk** [comment]
> Currently we use github.com/codegangsta/cli as the command-line tool library/framework for all 0-stor binaries.


Actually the 0-stor cli use another lib `github.com/urfave/cli`

> The goal of this issue is to decide which of those 2 we want to keep using, so we can use the same Command-line tool framework for all 0-stor/0-disk/0-tlog binaries.

We need to decide sooner because i need it for client proxy.

I myself doesn't have any preference for this

**Comment by GlenDC** [comment]
> Actually the 0-stor cli use another lib github.com/urfave/cli

github.com/codegangsta/cli redirects to github.com/urfave/cli, I think it has been moved namespace, but search engines still have the old namespace cached.

**Comment by GlenDC** [comment]
And personally I favor https://github.com/spf13/cobra. It feels a lot cleaner to me. Plus it can be combined with other libraries of the same other (e.g. https://github.com/spf13/viper for advanced configuration supporting all kinds of config files as well as environment variables). All in all it feels like a much more complete solution. Plus I really like the clean structure cobra provides.

For ztordb it doesn't matter too much, as it's just some flags and no commands. But for tools such as ztorctl and ztorproxy it does matter, as they have quite some commands, and the current structure really is not easy to read at all.

I also know a lot more big projects that use cobra, giving me a lot more trust in it. cli does have a lot of stars, so I suppose it is used by some big names as well, but I didn't knew about it until I saw it in this project.

So unless someone objects, I think we should drop cli and go for cobra. If so, I'll also add the needed task to this to do this for the client (ztorctl). The server (ztordb) can switch to cobra as part of issue #328 (the final task of #322).

I will close the issue tomorrow if no one objects.

**Comment by GlenDC** [comment]
https://github.com/spf13/cobra is the framework of choice
