### ISSUE TITLE
Implement and use the new server encoding package

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#325]
+ [x] Remove the objects/namespaces/storeStats files from the db package;
+ [x] Remove the manager package;
+ [x] Define, implement and test the encoding package;
+ [x] Define the public types in the root server package
       (see: https://github.com/zero-os/0-stor/blob/master/specs/server.md#server-package);
+ [x] Adapt the GRPC server code as to make it use the new code
    to support the features/API it was already supporting;
+ [x] ensure package is properly unit tested;
+ [x] ensure unit tests cover at least 80% of the code;

More information: https://github.com/zero-os/0-stor/blob/master/specs/server.md#encoding

**Comment by GlenDC** [comment]
Ensure to look at https://github.com/zero-os/0-stor/issues/305#issue-275052378 for inspiration about how we can document the encoding formats (to be done for each encoding function. Don't follow the comment there strictly, it serves just to give you ideas and inspiration.

**Comment by katia-e** [comment]
@GlenDC 
> Remove the objects/namespaeses/storeStats files from the db package

Does it mean that store_stat.go, object.go and namespace.go will become a part of new encoding package"

>Remove the and management package;

Was the server/manager package meant?

**Comment by GlenDC** [comment]
@katia-e this task cannot be done yet. Check the order of server tasks in issue #322. There are other tasks that have to be finished before this one can be done.
