### ISSUE TITLE
Support xz for (de)compression

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#330]
There are Golang libs for available. The one we use for 0-Disk backups is: https://github.com/ulikunitz/xz

It's not as fast as `lz4` or `gzip`, but it has a much better compression rate.

**Comment by zaibon** [comment]
I think we should allow user to select which compression algo he wants to used based on it's need.
Some would prefer to have faster algo while other would prefer better compression rate.

**Comment by GlenDC** [comment]
Thanks to the feature allow users to register their own compression algorithm and integrate it in the configuration-based creation (see #393), this issue is no longer desired.

Closing it, as the user will be able to support xz for themselves if desired.
