### ISSUE TITLE
replace client lib READMEs with Godocs

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#331]
For some reason all lib components now have a markdown README.me file.

The documentation part of it should be simply added to the main file (e.g. `chunker.go`), or a `doc.go` file if you really want that, but I wouldn't really do that in the case of these small packages. This kind of package documentation has to be added to the top of the file (above the `package` statement).

As an example, that would mean something along the following lines for the chunker package:

```diff
diff --git a/client/lib/chunker/chunker.go b/client/lib/chunker/chunker.go
index 3490458..3cf7b46 100644
--- a/client/lib/chunker/chunker.go
+++ b/client/lib/chunker/chunker.go
@@ -1,3 +1,8 @@
+// Package chunker defines a pipeline component
+// to split a block into multiple smaller blocks.
+//
+// Chunker returns an iterator that will yield a new chunk of data of the choosen size.
+// The block can then be sent to the rest of the pipeline.
 package chunker
 
 import (
```

The example written in the README.md file should be added into a new file (one for each component package), named `example_test.go`. This way the example will be both added to the package Godocs, as well as be run alongside the other unit tests. This ensures that the example stays in sync with the code.

By doing these changes we:

+ Keep the documentation in reach of the programmer:
  + The programmer can read the docs directly alongside the code;
  + The documentation will be available in its natural habitat on Godocs;
+ Ensure that the examples are correct, will stay in sync with the code and can be copy pasted;

The following component packages have currently such a README.md file that will have to be transformed to Godocs documentation and runnable example tests:

+ [ ] `github.com/zero-os/0-stor/client/lib/chunker`:
         https://github.com/zero-os/0-stor/tree/master/client/lib/chunker/README.md;
+ [ ] `github.com/zero-os/0-stor/client/lib/compress`:
          https://github.com/zero-os/0-stor/tree/master/client/lib/compress/README.md;
+ [ ] `github.com/zero-os/0-stor/client/lib/distribution`:
         https://github.com/zero-os/0-stor/tree/master/client/lib/distribution/README.md;
+ [ ] `github.com/zero-os/0-stor/client/lib/encrypt`:
          https://github.com/zero-os/0-stor/tree/master/client/lib/encrypt/README.md;
+ [ ] `github.com/zero-os/0-stor/client/lib`:
          https://github.com/zero-os/0-stor/tree/master/client/lib/README.md;

While transforming those examples and documentation:

+ Ensure to improve/fix the documentation as you go. Don't be shy to expand the documentation, as I'm sure it can use some improvement;
+ When writing documentation, at the very least also run it through a English (US) Spellchecker, this never hurts;
+ Ensure to improve/fix any mistakes in the examples;
+ If you think some examples are missing, add them as well;

You don't have to publish your code to the github master branch to see your Godocs rendered. You can run godocs locally by:

1. run godoc on port `6060` (or any free local port): `$ godoc -http=:6060`;
2. open a browser and surf to: http://localhost:6060/pkg/github.com/zero-os/0-stor/client/lib/#pkg-subdirectories
3. enjoy reading your rendered documentation and seeing your examples

Pro tip: you can modify your godocs code (examples/documentation), save the file and simply refresh the web page. It will automatically re-render your update.

Here are some links to some related golang documentation:

+ https://blog.golang.org/godoc-documenting-go-code
+ https://blog.golang.org/examples

**Comment by katia-e** [comment]
@GlenDC , a question regarding ``client/lib/distribution``` package: 

Example in [README](https://github.com/zero-os/0-stor/tree/master/client/lib/distribution) contains functions that are not present in package `distribution` any more. Perhaps the package was entirely changed, while the example wasn't. Right now I can't quite correspond the example with functions in the package and don't see understand which part of the code does distribution, and what is seen as distribution.

**Comment by GlenDC** [comment]
Right now it just seems to be as simple as using the (*Encoder).Encode and (*Decoder).Decode methods. You would use the first to do the distribution and the latter for restoring.

You don't need to literally copy that example code, @katia-e. You just need to make sure that the examples show how to use that component in its current state.

The fact that those examples are sooooo out of date, shows once again why we really shouldn't write examples like that in deep-nested markdown files. It's just asking to get out-of-date.

**Comment by katia-e** [comment]
@GlenDC, another question related to the same distribution package. In README there is this bit about distribution methods in client, but there is nothing from readers and writers defined in this package. Shall this bit go to the client package, or shall it stay in distribution?
```
- We use 2 types of distributors in client
    - Generic distribution
        - input/output are io.Reader/io.Writer
    - Stor Distribution
        - Save a chunks of data in 0stor cluster
        - Save metadata about all chunks of file and where they are in a configuration server such as [etcd server](https://github.com/coreos/etcd)
        - If we are using chunker (../lib/chunker) pipeline, then we probably need to use  [metadata pipeline](../meta/README.md)
        in order to save all needed info/metadata to reconstruct file back from chunks into [etcd server](https://github.com/coreos/etcd)
```

**Comment by GlenDC** [comment]
Dunno, I think those docs are out of date.

If you grep `distribution\.NewEncoder` and `distribution\.NewDecoder`, than you'll find that the only thing that we ever encode and decode is raw byte slices.

I think for now you can just delete it. We can always revive some of it if needed. But I don't think that will be required, as it doesn't seem to helpful of a text anyhow.
