### ISSUE TITLE
support secure GRPC (stor) client

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#333]
Currently it seems like we only support an insecure GRPC client, as can be seen in:

https://github.com/zero-os/0-stor/blob/8f27878b3a4b1a06f7f42e92c6d923a7d0cd0048/client/stor/client.go#L60-L72

Also, I would redefine that constructor as `NewGRPCClient` and move that to the `client/stor/grpc` package.

**Comment by GlenDC** [comment]
Using https://godoc.org/google.golang.org/grpc/credentials we can support a secure TLS/SSL connection. I think the `NewClient` function should require the required CERT Files as input, and we should make an alternative constructor called `NewInsecureClient`, to be really explicit about the fact that this is insecure and we do not support it (hence the longer and more explicit name). The `NewClient` function is the one that creates a secure client using TLS/SSL credentials.

For the 0-stor (command-line) client we would than use one of two constructors, depending if a certificate is given or not.

**Comment by GlenDC** [comment]
@zaibon I have pretty much a solution ready. The only blocker is that I'm not sure what to do with unlisted zstordb shards which require a TLS configuration. As we only store the shardID there is currently no TLS configuration available for any unlisted shard (that is, a shard which is referenced in a chunk, but which wasn't part of the listed shards in the Client Config).

And Storing the TLS config as part of the metadata is both inefficient and insecure. So not sure what to do with this one...

Deep inside me this just confirms what I've told you when I was redesigning the 0-stor codebase. That is, that the concept of unlisted shards is pretty weird, and should probably not exist. To me, having an unlisted shard, means you are not controlling your own data, and it means you really have an issue somewhere in your user-setup.

If we would limit ourselves to listed shards only, this last blocker is resolved, and I can finish my TLS support.

What do you think, @zaibon?

**Comment by GlenDC** [comment]
According to @zaibon we cannot get rid of unlisted shards, as some use cases (such as the 0-hub/0-fs use-cases) rely on the fact that all or some shards might not be known and can thus not be listed. How this works, or why this is even desired, is beyond me at the moment, but so be it.

Either way, I'm ok with this, but when you don't even know which shards are there at all, you can not even rely on certificates with wildcard domains. Thus having a global TLS config, working for all shards (including unlisted ones) is thus not an option either.

Further we cannot (or rather shouldn't) store the TLS config as part of the shard either, because:

+ This is inefficient (you would have to store it for each shard, which is a lot of extra metadata to store (as the TLS config is/can-be really big);
+ This is not flexible enough as TLS configs tend to update (e.g. renewing certificates, rotating keys, ...), which would force us to having to update all shards somehow. But how would that even possible, as we have no clue about these configs, we can also not really know that such a config update is supposed to happen;
+ It would be pretty insecure to store such sensitive information in a database (e.g. ETCD);

So yeah. First I really need to get convinced that this unlisted shards feature is really that desired. To me it really seems like a hack, and I do not see any benefits to it at all, other than making our lives difficult. I do not understand why you would ever want to read data from a shard, without being able to know up front where it comes from. At least in the context of 0-stor that really doesn't make sense to me, but probably there are good reasons for why this is needed. So someone really needs to help me convince myself of why this feature is required and what use cases we have exactly in mind for it.

And more importantly, if we require this unlisted shards feature, than we're really in trouble, and will have to find a way to provide TLS-backed secure connections none the less. I guess you could work with a proxy service that can provide us those TLS configs, but I'm not entirely sure how that would be useful, or even secure. So I don't think that's a solution either...

**Comment by zaibon** [comment]
Let me explain the use case we have where some 0-stor client wouldn't know about some shards.

We are planning to [upgrade the backend of the 0-hub with 0-stor](https://github.com/zero-os/0-hub/issues/29). So the 0-hub will use N number of 0-stor to create a distributed cluster of 0-stor in order to make the data more secure and repairable.

One user of the 0-hub is the [0-fs](https://github.com/zero-os/0-fs). The 0-fs receive the information where do get the file system data from a special formatted file called flist. So the 0-fs is not aware of where the data it needs is when it starts. Also, we could make some change in the 0-stor cluster an any moment, so some shards may be added or deleted. 0-fs needs to keep working when this happens.

This is why we can't really drop support for unlisted shards. 0-fs will only ever use shards from the metadata contains in the flist and never know them before hands when creating the 0-stor client.

**Comment by zaibon** [comment]
Now I'm wondering. I didn't check how secure connection works for grpc, but since it's on top of http2.
Do we really need to have client certificate ? Can't we have a server certificate that is signed by known CA, like any browser does ?

**Comment by GlenDC** [comment]
> Do we really need to have client certificate ? Can't we have a server certificate that is signed by known CA, like any browser does ?

Yeah in theory it could work, as long as we know up front all needed public keys. That can be one, or multiple. As long as we have those, than yes it can work.

Sounds like a reasonable solution, and makes the configuration a lot easier as well.

Shall we go for that road @zaibon?

**Comment by zaibon** [comment]
> Yeah in theory it could work, as long as we know up front all needed public keys

Which public keys are we talking about here ?

**Comment by GlenDC** [comment]
> Which public keys are we talking about here ?

The root pem of the server(s). But as you have many servers, it might be possible to you have server group A using/require key (pem) A, while server group B uses/requires key (pem) B. So all those pems we need to have up from I suppose to have this work.
