### ISSUE TITLE
Why is there a 0-stor meta client implementation using Redis?

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#336]
There is a 0-stor meta client implementation using Redis (which can be used to interface with any server that supports the redis API), which can be found in https://github.com/zero-os/0-stor/blob/master/client/meta/redis/client.go.

Yet, I don't see it being used or referenced.

Even crazier, I don't see how you could ever create a 0-stor Client (https://godoc.org/github.com/zero-os/0-stor/client#Client) using that redis client. As the Policy (https://godoc.org/github.com/zero-os/0-stor/client#Policy) seems to have no configuration to use redis (for meta) instead of etcd. And as we _should_ never use the Meta client directly (and always use the 0-stor client which wraps the Meta client), it really doesn't make any sense to have that Redis client implementation, when it can never be used at all.

So I see two choices:

+ Either we keep that Redis meta client implementation, and make sure that a 0-stor client can be created using Redis instead of ETCD for metadata;
+ Or we remove the Redis meta client implementation, so we no longer have to maintain something that has no purpose at all;

Or perhaps (and I think this might be more logical), we should not make the MetaData client part of the policy, and instead take a Meta client interface value as part of the `New` constructor, so that the user can also provide their own Client implementation (and this way the Redis Client could be used instead of the MEta client if desired).

**Comment by zaibon** [comment]
The redis implementation has been investigated when we had some performance issue with etcd.
But it's indeed not used anywhere and nothing has really been decided regarding another metadata store so I think we can clean up the code base from the redis implementation.

I also like your idea of providing a way to the user to specify is own metadata store. But if we don't make it part of the policy. Then how is the CLI will know what to use, cause there you can't specify a store client.

**Comment by GlenDC** [comment]
> But if we don't make it part of the policy. Then how is the CLI will know what to use, cause there you can't specify a store client.

Of course they can. The CLI isn't magical he. It's just flags and code.

I do see why you're saying it, as the way the code is currently structures, where the policy is assumed to be the entire config file (and you can't validate yourself when you unmarshal a policy yourself (indirectly)), so I do understand where you're coming from with this.

But I think that's a super minor issue. We can easily fix that policy and configuration part. In general I think there is a lot of improvement around the entire policy/client constructing thing. So this could just be another one of those improvements.

I certainly don't think that's enough reason _not_ to go for allowing the user to provide her own Meta client. What do you think @zaibon.

**Comment by GlenDC** [comment]
> But it's indeed not used anywhere and nothing has really been decided regarding another metadata store so I think we can clean up the code base from the redis implementation.

And ok I'll resolve this issue already, by removing the redis client than, and all dependencies that are vendored for it. It will be than up to the user of the 0-stor client library if she/he wants to define a custom meta client (e.g. redis).
