### ISSUE TITLE
create GRPC middleware to gather requests stats

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#346]
In the same vein as #317 we should also move the gathering of statistics into a middleware. 
Current in each grpc handler we do something like https://github.com/zero-os/0-stor/blob/65060292f43a0c20a356f8c8b1e8004a14ba859f/server/object_api.go#L30

This should be moved out of the handler and moved into a middleware.

The only thing I'm not sure about his how we can  deduct which type of request (read/write) it is from the middleware.

**Comment by GlenDC** [comment]
I think you would do similar stuff as what you would have to do for the JWT Verifier middleware code.

To get the label you would have to do something like

```go
labelGetter, ok := req.(interface{GetLabel() string})
if !ok {
    // return early I guess? Dunno if this should count as an error
}
label := labelGetter.GetLabel()
```

And for whether or not this read or write, I suppose you could define a type to indicate whether the MethodName is doing a read, a write or nothing of the 2. If so you could define a private mapping, to define what stat should be checked:

```go
methodType, ok := methodTypeMapping[info.MethodName()]
if !ok {
    panic("non-recognized method")
}
switch methodType {
    case read:
       stats.IncrRead(label)
    case write:
       stats.IncrWrite(label)
}
```

For the JWTVerifier you'll have to have a similar mapping, but there you would map each MethodName to a `jwt.Method`.

The label logic is the same for both middleware I guess.

This is just some pseudo code and ideas though. I don't know the GRPC API too well, so some stuff might be different. Also I think the MethodName it exposes to middleware is the complete MethodName as in `/package.service/method`, so you'll have to probably do some string manipulation as well, before you check your Method mapping.
