### ISSUE TITLE
remove EncrKey from 0-stor client Meta

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#350]
Currently we store the EncrKey as part of the Meta struct for each key we write. This means that we're currently storing a private key in plain text into ETCD...

First of all, I do not understand why we're storing the private key in the first place? I don't see the need for it, and we're not even using it. (I gepped for `.EncrKey` and I never saw it being read-accessed, except in some unit test).

Second of all, this is completely insecure. It's like storing passwords in plain-text into databases, it's not something you would ever do (hopefully).

The simplest solution is in my eyes also the best one, remove this property.

**Comment by zaibon** [comment]
fully agree, should never have been there. I move this in priority critical.
