### ISSUE TITLE
Client (re)design proposals

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#367]
After some reflection, and before I start working things more in detail in a spec, I would like to list some (re)design proposal I have in mind:

## Simpler code, More flexibility

Right now we create the client using a policy config struct. It allows you to configure the servers, and the block size. Than it also has some limited configuration for the components. But all in all it is very restrictive.

Now this does seem right more or less for the `zstor` cli client, even though I would still want it to be more flexible even there. However for an API (Golang lib) that is really way to restrictive.

+ We define components, yet some of them we don't use (e.g. we hard-code snappy compress directly);
+ The components have a weird, not really usable design;
+ There is no real pipeline design there, certainly nothing that is really re-used throughout the API;
+ The user cannot define its own components (and certainly cannot use them when using the 0-stor client);
+ The user has little control over the components it does use (e.g. the different compress algorithms have a lot of configuration available, but the user cannot touch any of it);

I propose that we keep the code a lot simpler. I haven't worked out exactly yet, but I certainly would do away with the entire policy thing. I agree that we will define some config for the `zstor` cli client (even though that one will be more flexible than the policy currently is), but for the API this isn't needed.

I would want to have a client:

+ Which does always use a stor-clients for the data servers, I don't think it makes sense to customize this;
+ The IYO config becomes (semi-)optional,as a separate IYO config struct, as the `zstordb` can disable authentication, so this might not be needed;
+ I suppose there will still be some other config as well (e.g. the block size);

However:

+ Rather than creating a metadata client, I think that should be given by the user, and by default it is simply `nil` (and thus we have a more limited API in that case;
+ We should have some generic pipeline object/structure/design, where we can plugin an entire chain of components, with whatever components, in whatever "reasonable" order (it's up to the user to make sure the order make sense, hard to validate this, and why would we care);
+ This way the user can define whatever components she wants, and use whatever components;
+ This also allows the user to create the components objects manually (using the component constructors), making it much easier to expose a per-component configuration for a more fine-grained configuration;
+ None of these components should be hidden behind an interface, even though they will probably implement some component to make them pluggable into the pipeline;

Lastly:

+ As discussed before, we'll want to make the pipeline parallel and streaming (non-blocking), so that we're constantly doing a lot of work at the same time, rather than doing big chunks of work before passing it to the next stage;
+ So that we can do multiple different stores at the same time;
+ The global client interface can just be killed, there is no need for us to expose a Client interface. This object is waay to non-generic for that. If you talk about some kind of small generic object than exposing an interface is fine. But for something the client it doesn't make sense for us. If the user wants to define an interface for it (e.g. to have a stub), than the user can define it herself. We want to expose it simply as a public concrete type directly;

Also the Hasher component is never used. And the replicator never became a component, and instead is just a collection of functions somewhere in the client code.

## Normalize keywords

Currently we use a lot of different keywords (to indicate action), while they all mean the same thing. Here are some examples:

+ Remove == Delete
+ Set == Create == Put == Give

We cannot control the keywords used by APIs that we use (e.g. IYO), but that does not have to mean we expose the same keyword. I would really recommend to choose a keyword for each purpose, and than use that same keyword for all API methods throughout the entire 0-stor codebase. This will make the API simpler to use, as you don't have to worry about whether it was Put or Set or Create.

## Minify Client API

Rename `WriteF` and `ReadF` functions to `Write` and `Read`, and get rid of the wrapper `Write` and `Read functions`.This way the user can write/read whatever, and it's simple enough to define a byte.Buffer if you really want to simply write a byte.Buffer, but I think in most (serious) cases you actually do want to read/write using some kind of streamed type. It also gets rid of the very non-performent `Read` function that is currently defined;

In general you want to keep an API as small as possible. Providing wrappers like this, can easily be done by the user, and should really not be defined by us.

Further I'm still not a big fan of giving the client all these methods though.I think it would be acceptable to have a `IYOClient` that we expose, that provides the permission/namespace functionality. It's still part of the 0-stor client API, but it doesn't have to be all embedded in one structure.

And obviously that wouldn't make developing the `zstor` tool any more difficult, and there it can still look like it's all unified.

**Comment by GlenDC** [comment]
That's about it, at least what I can think of from the top of my head, and going through my notes. I'm sure there is still some smaller stuff that can be improved, but this is the bug stuff.

Please let me know what you think of it, @zaibon. Planning to work them out tomorrow (29/11) in detail when I start working on an actual spec. So that things that are still vague in my head (e.g. the entire generalized client pipeline concept) become concrete as well. Other things are already pretty clear and are pretty much defined in this issue as well.

**Comment by iwanbk** [comment]
> There is no real pipeline design there, certainly nothing that is really re-used throughout the API;

> We should have some generic pipeline object/structure/design, where we can plugin an entire chain of components, with whatever components, in whatever "reasonable" order (it's up to the user to make sure the order make sense, hard to validate this, and why would we care);

we had pipeline before, and then removed it.
@zaibon has better info about the removal reason.

**Comment by zaibon** [comment]
> We define components, yet some of them we don't use (e.g. we hard-code snappy compress directly);

Result of a quick not super clean refactor to get shit done. Need to be cleaned up.

> The components have a weird, not really usable design;

Which one ?

> There is no real pipeline design there, certainly nothing that is really re-used throughout the API;

This is something I want to fix to, We need a way to allow proper concurrency, would that be using pipeline or something else.

> The user cannot define its own components (and certainly cannot use them when using the 0-stor client);

This is mostly by design. 

> I propose that we keep the code a lot simpler. I haven't worked out exactly yet, but I certainly would do away with the entire policy thing. I agree that we will define some config for the zstor cli client (even though that one will be more flexible than the policy currently is), but for the API this isn't needed.

We cannot get away from the policy. The concept here is that we can serialize the policy, save it somewhere and then a another client, just using this policy should be able to get the exact same client setup. (same component enabled, same data shards,...)

> The IYO config becomes (semi-)optional,as a separate IYO config struct, as the zstordb can disable authentication, so this might not be needed;

I think this is reasonable, now that we can have non authenticated namespace.


> We should have some generic pipeline object/structure/design, where we can plugin an entire chain of components, with whatever components, in whatever "reasonable" order (it's up to the user to make sure the order make sense, hard to validate this, and why would we care);

Agree on the pipeline idea if it to improve performance and give better concurrency. But we will not let the user plug stuff manually. The configuration of the client and its behavior have to come from the policy he defined. 
We have only one flow : chunking, encryption, compression, distribution/replication. And user can enble or disable some of the steps.

> The global client interface can just be killed, there is no need for us to expose a Client interface.

Which client interface are we talking about here ?

> Normalize keywords

That sounds right.

> Minify Client API

We can reduce the client API in exchange with nice example how to create these wrappers.
And moving the IYOClient out of the client itself doesn't bother me either.

**Comment by GlenDC** [comment]
> We cannot get away from the policy. The concept here is that we can serialize the policy, save it somewhere and then a another client, just using this policy should be able to get the exact same client setup. (same component enabled, same data shards,...)

I don't agree with that at all. The only place where you really need a serialized config is the `zstor` tool. I'm not saying you can't expose that zerialized config somewhere, but I don't see why it's required for the Go API. I mean in our use case we might never want a custom pipeline, but I don't see why we have to limit that? On top of that there are so many options that are now hidden behind this limitation...

> Which client interface are we talking about here ?

Nevermind, I don't think that one exists.
