### ISSUE TITLE
Define the different kind of benchmarks

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#372]
Define the different kind of benchmarks we want for the 0-stor project. I suppose we have them on two levels:

+ On a package level: these can be just written as standard Golang `Benchmark` funcs in the `_test.go` files.
+ On a system level: these would be separate Golang projects which we can easily launch (perhaps with some optional flags) that would do everything so we can do it from the push of a button (this would mean they also spawn the needed servers as part of the execution);

For both levels, it will be useful for us to define up front a detailed list of what kind of benchmarks we definitely want, and also in what order they are helpful.

**Comment by zaibon** [comment]
> On a package level: these can be just written as standard Golang Benchmark funcs in the _test.go files.

How I see it, these package level benchmark should be created as we have the need for them. 
So one we have numbers from the system benchmark and identify a bottleneck we write a Benchmark func for this specific portion of the code. So it's easy and faster after to iterate on that portion of the code to improve it.

Then regarding system benchmark.

I thing we should test different layers of the 0-stor. Most of the logic and data processing is in the client. So I think it would be worthy to have some test that only benchmark the grpc layer. So we can know the real raw throughput of the server.

Flags for these tests, What we want to be able to configure:
- Deploy 0-stor server on top of different kind of disk. both for value log and lsm tree.
  - kind of disk to test, SSD, HDD, memory. 
- Configure the GOPROCMAX number for the server
- With or without authentification enabled.
- Size of the data send from the client.  Both for keys and data.
- Number of concurrent connection to the server. So we tune the number of client and how much concurrency is done client side.
- Async write enable/disabled for badger.

Then we have need benchmarks that test the full system. So multiple 0-stor server and some client that does that full data processing. For this we need to be able to tunes:
- Number of 0-stor servers
- different configuration for the client. (block size, replication, distribution, different hashing and encryption algo)
- Number of concurrent pipeline created
- Number of client connections.

It should also be able for the user to ask some specific profiling during execute of the tests, (CPU, Memory usage,  blocking profile,  contended mutexes).
Server and client should also support [golang tracing](https://golang.org/pkg/runtime/trace/)

All of the benchmarks, should produce data and graphs. library to plot graphs need to be chosen.
