### ISSUE TITLE
replace CRC as a way to detect duplicated content

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#41]
CRC is for error/corrupt checking.

**Comment by zaibon** [comment]
fixed by : https://github.com/zero-os/0-stor/pull/44

**Comment by despiegk** [comment]
???
CRC is a way how to check indeed corrupt checking, we should not do dedupe !!!
where do we do dedupe?

its up to the user of the system to define the key used
this can be a hash key or something else, this is irrelevant to us?

**Comment by despiegk** [comment]
CRC is much cheaper than hash, so we should not just replace hash?
I don't see where we need to hash in this proj anywhere?

**Comment by iwanbk** [comment]
If user try to store with same key but different payload, server returns 409 (conflict).
CRC was being used to detect this difference

**Comment by zaibon** [comment]
We will not validate data in the 0-stor anymore, but expose reference list to the user. So it's not up to use to increment/decrement reference. So no need for hash
