### ISSUE TITLE
provide pipeline model and master-client for metastor

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#418]
Currently we already allow people to define their own metastor, by implementing and using an instance of the following interface: https://github.com/zero-os/0-stor/blob/7ee85f40ec92cf1feca8896d696b27520cb9528d/client/metastor/interface.go#L22-L45

This is simple enough, as we require only 3 methods (well 4 if you still can count Close, but I think we can remove that from the interface, as closing is something optional to the implementation, as there might be implementation who don't need it.

However. This does mean that we require each implementation to define all the encoding and processing. To move between the `metastor.Data` to raw binary format (`[]byte`). In a way this is already partially resolved, by the introduction of the `metastor/encoding` package (https://godoc.org/github.com/zero-os/0-stor/client/metastor/encoding), which allows metastor-client implementors to delegate the encoding work to an implementation provided in that package.

However, should an implementation require compression and encryption, than this currently has to be written separately for each implementation. I can also imagine that distribution might be a pipeline feature we might want to support, so we can provide more resilience for our metadata (e.g. using erasure coding). Whether that simply means writing to multiple local directories or multiple shards (servers), is up to the implementation of course. Especially encryption is a feature, that we're missing here, and that triggered this line of thinking.

So with that in mind, and especially just focusing on having `encoding->compression->encryption` as part of the metastor pipeline model, I think we could define the following `DB` interface:

```go
// package metastor/db
type DB interface {
     Set(key, data []byte) error
     Get(key []byte) ([]byte, error
     Delete(key []byte) error
     Update(key []byte, cb func(origData []byte) (newData []byte, err error)) error
}
```

And use that interface as part of one (to rule them all) metastor client (structure), which would use the DB interface, as well as a pipeline interface, to provide the following (fixed) API:

```go
// package metastor
type Client struct {
   // ...
}

func (client *Client) SetMetadata(meta Data) error {
   // ...
}

func (client *Client) GetMetadata(key []byte) (*Data, error) {
   // ...
}

func (client *Client) DeleteMetadata(key []byte) error {
   // ...
}

func (client *Client) Close() error {
   // ...
}

// Yes, as you can see,
// it is basically the API of the currently provided Client interface,
// as that API is good enough, but we simply want to turn it into a fixed structure,
// and have people define the underlying interfaces (e.g. DB) if desired instead.
```

So as I said, besides using the DB interface (for storage), the metastor client (structure), will also make use of some kind of pipeline interface (replacing and composing the current encoding stuff):

```go
// package metastor
type Pipeline interface {
   Write(meta Data) ([]byte, error)
   Read(key []byte) (*Data, error)
}
```

If we go down this road, we can probably move the `datastor/pipeline/processing` package, to become a subpackage of the root `client` package, so we can share it between the datastor and metastor. This way we can turn our encoding logic, that we already have, in a metastor-specific processor in the metastor package, and simply make use of the the combination of that, to without having to write too much, suddenly be able to provide a feature-rich metastor client, which can easily be customized to fit the users needs.

And by default we could still have encoding as the only processor, with the default (and only standard-provided encoder) being gogo-protobuf.

This makes it also easy for people to provide their own storage for the metastor (e.g. be it Badger, as we'll provide, or be it something else like Redis or even SQL), all it would take is implement the simple DB interface, which is basically just wrapping around the Golang API of the storage used, in most cases, while the user would still benefit from all the features that we provide for all implementations, for free.

**Comment by zaibon** [comment]
I like the idea to be able to also encrypt the metadata. And re-using the pipeline mechanism already present seems like a right approach. 
Would like to see how much it complexify the configuration though.

I'll also move this to next release since this is not a blocker for beta-2
