### ISSUE TITLE
provide a badger-backed metastor client

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#419]
The 0-stor client requires a metastor client, to manage all the metadata, which we require as part of that client. While the user can provide a custom implementation already, it would still be great to provide a metastor client, which makes use of the local FS, as to provide a simple (and etcd-free) way to make use of the 0-stor project.

As we're happy with Badger, we already rely on it as a dependency, and as Badger also makes use of the local FS for storage, I think it would be a great choice to provide an alternative client.

On top of that I would even suggest to make Badger the default metastor client, as it doesn't require anything from configuration from the user, and just works out of the box.

**Comment by GlenDC** [comment]
I would suggest to wait with the development of this feature, until we agree and figure out all details of issue #418. Once that's the case, we can probably resolve that issue and this issue as part of the same PR.

**Comment by zaibon** [comment]
I would love to have  more metastor implementation. ETCD has proven not to be scalable/fast enough for our use cases.
But making the local FS the default implementation, I'm not sure.

Let's see what comes out of #418  and we'll advice then

**Comment by zaibon** [comment]
moving to beta-3 since it depends of #418 and it is part of beta-3

**Comment by GlenDC** [comment]
> moving to beta-3 since it depends of #418 and it is part of beta-3

I don't think it has to depend on #418, at least not to resolve this issue. So I'll already just implement a simple client as it is, so that it at least can be used by the experimental folks who want to get their hands dirty without having to rely on ETCD.

Later I can than work out the details of #418, and develop that separately, once we agree on the details of it.
