### ISSUE TITLE
provide better gen-key-templates for datastor objects created by 0-stor client

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#421]
When writing a "file" using the https://github.com/zero-os/0-stor/blob/7ee85f40ec92cf1feca8896d696b27520cb9528d/client/client.go#L129-L131 function, we do so giving a key. This is however the key of the file/metadata, and not the keys of the single or multiple datastor objects dat will be used for storage of the actual data of that file.

The keys for the single or multiple datastor objects, containing the data of that "file", are automatically generated, using a cryptographic hasher. This is done by checksumming the raw data (as in the data before any processing is applied) and on top of that, when a private key is provided, a signature is created using that checksum and the private key as input.

While this is great on paper, it brings perhaps, an unforeseen consequence with it (as I hope this is just due to oversight).

It means that when storing multiple files, using the same configuration, blocks will be shared, if they are stored on the same (zstordb) shard. Meaning several things:

+ When deleting a "file" using the 0-stor client, it simply deletes all datastor objects stored for that file, no matter if that object is also used by other "files" (this is a big problem, and is very likely to hit users right in the face very soon);
+ Reference lists will simply be overwritten, if a datastor object gets created on a shard, where  that content already existed, previously (this is only the case if the second file also makes use of the reference list, otherwise the reference list will not be touched, which would mean that this second file suddenly has a reference list (which it will retrieve when reading the file), even though it didn't make use of references at all, which is a related, but different, problem);

For the Reference lists I already started an issue, #420, as it fits in a bigger picture, of rethinking the reference-support, as there are more problems with it, than just the one thing mentioned here.

So for this issue I would like to focus mostly on the first problem, that is, that a file might suddenly lose data, because it (unknowingly by the user?) shares objects between files.

Still, we might assume that the user owns the shards they use, and also chooses the private key, but the problem would still be there. The user might have many files, and as long as you have enough files, which are large enough, and a small enough object size (e.g. 4KiB), you'll very likely start sharing objects, very soon.

The simplest, most naive, solution would be to prefix all datastor objects, when generated via the 0-stor master client, with a namespace + "file"-key. It can however never be as simple as this, as this would mean that having deduped files, is no longer possible, should this be something the 0-stor user wants to have. Still, all is possible, by extending the configuration, but I don't think the solution can be as simple as this, as for sure there would be other issues coming with that approach.

First of all I think it needs to be clear what kind of options/use-cases we want to open up for our users. Do we ever want to support deduped content? if so, this needs to be taken into account, just like all other requirements that we establish. Once that's clear, we should try to come up with a robust solution, that can handle all this, without creating problems as we have with the current design.

**Comment by zaibon** [comment]
This is indeed a big issue.

I tried to come up with some solution, but as long as we don't allow the user to choose the key of the datastor object them self, I don't see how we can allow the user to implement any kind of dedupe mechanism.

On the other hand I start to wonder if we should allow dedupe at the 0stor level. And if it should no be left to a layer on top of the 0-stor when implementing a solution.

But then that quite defeat the purpose of the reference list altogether.

Some thing to think about...

**Comment by GlenDC** [comment]
For now, to keep things simple and working, all files stored will be stored using a unique key, as to avoid any of the current problems we have with our hash-based keys.

The key will be just an incremental ID, generated and provided by the zstordb server, unique within the context of its namespace. For this we'll use Badger's support for sequences (https://godoc.org/github.com/dgraph-io/badger#Sequence). We'll keep one per namespace in-memory, with some room for bandwidth.

This does mean that the GRPC interface will change, as no key will have to be given any longer to `SetObject`, and instead the key will be defined by the server and returned as the response for that method for this feature to be implemented.

For now we'll drop hashes, but we might revive hashing back, in the `beta-3` milestone, as an optional (pipeline) feature, to provide deduplication for those who want it.

**Comment by GlenDC** [comment]
The proposed solution has been implemented in 8da04fc06a7731a2abf490da5f559355f1b9ffa0.
