### ISSUE TITLE
make metadata accessible in 0-stor master client and daemon

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#429]
The new/current design, as introduced as a solution for #386, hides the metadata completely a way from the public API. As can be seen if we quickly summarize its current (core) API:

```go
func (c *Client) Write(key []byte, r io.Reader) error {}
func (c *Client) Read(key []byte, w io.Writer) error {}
func (c *Client) Delete(key []byte) error {}
func (c *Client) Check(key []byte, fast bool) (storage.CheckStatus, error) {}
func (c *Client) Repair(key []byte) error  {}
func (c *Client) Close() error {}
```

The reasoning was that this keeps the API cleaner, and if the user wants to access the metadata they could always define their own metadata client. However, this isn't acceptable for at least 2 reasons:

1. We should be able to handle our expected use cases, without having/require-our-user to write an entire client for that;
2. It is possible that even though the metadata needs to be stored in some location using the normal metadata client, we might still also want to have the metadata as a result, to use or store it in a secondary location. Just as well as might already have the metadata available, and wish to be able to fetch the data directly, without having to use chunks for that purpose;

On top of that we have the daemon project, which is used to expose the 0-stor client to other language environments using a common interface (e.g. GRPC). In that case we cannot really rely on the fact that the user can easily define their own interface, and thus we need out of the box solutions that users can use the 0-stor in a flexible enough way, as to fit their purpose.

**Comment by GlenDC** [comment]
As an initial proposal we could change the `Write`, `Read` and `Repair` methods to have the following signatures instead:

```go
func (c *Client) Write(key []byte, r io.Reader) (*metastor.Metadata, error) {}
func (c *Client) Read(key []byte, w io.Writer) (*metastor.Metadata, error) {}
func (c *Client) Repair(key []byte) (*metastor.Metadata, error)  {}
```

On top of these changes we could add the following methods:

```go
func (c *Client) ReadWithMeta(md *metastor.Metadata, w io.Writer) error {}
func (c *Client) DeleteWithMeta(md *metastor.Metadata) error {}
```

These changes and additions would provide the functionality that was taken away from the original client (due to the redesign). However I am not the biggest fan of it:

+ It makes the client API twice as big;
+ The WithMeta part of the names is not the best name in the world, but can't seem to find a better name;
+ These functions only cover some use cases (where somehow you want to store the metadata in 2 places, and have the metadata already pre-fetched and thus don't want to hit the metadata database, yet there are plenty of other use cases that these additions don't allow yet;
+ `ReadWithMeta` is a bit weird, as really all it needs are Chunks, so perhaps that should be `ReadWithChunks([]metastor.Chunk` instead;
+ `DeleteWithMeta` is a bit weird, as in, should it really delete the metadata as well from the etcd? I suppose so, but it feels a bit weird;
+ Even in the original client, `Repair` and `Check` was still only possible using the key directly;

The write function I wouldn't change, but in the future (beta-3?) I would like something like the following to be possible:

```go
func (c *Client) Write(key []byte, r io.Reader, optMetaData ...interface{}) error {}
```

But need to figure out on the exact signature, types and details. But the goal would be that custom metadata can be added to the generated metadata structure (e.g. linked list references, dedup metadata, ...).

Even though I don't like this proposal, doing these changes, and additions would allow the proposed use-case. On top of that we could provide a MetastorService in the daemon (GRPC) interface, which would simply expose the metadata client directly, so the other languages can also access the metadata directly.

I think we can do better than this proposal, but it is here none the less.

**Comment by zaibon** [comment]
As for beta-2 this is good enough. We can still take some time in next release to think more about how to provide generic metadata support. 

> It makes the client API twice as big;

Not a problem

> ReadWithMeta is a bit weird, as really all it needs are Chunks, so perhaps that should be ReadWithChunks([]metastor.Chunk instead;

It's feel more natural to pass the same object that you got from a write then something different, Here we clearly see that you just need to pass what you've been given, easy.

This proposal is not your favorite but this would allow us to have the python client to map to be map one on one with the go interface. So super easy to do. 
In next release we can come up with something nicer for metadata management.

**Comment by GlenDC** [comment]
> In next release we can come up with something nicer for metadata management.

Perhaps that's true, but I had hoped we could start to lock down the API already, but yeah...

> to be map one on one with the go interface

That's only partly true. It's true that if we also expose the metastor client as a GRPC Service, next to the regular/datastor client, that we indeed expose those APIs directly to any other language.

However libraries like the Python library, will always be limited to the stuff we provide by default. So they won't be able to provide their own metadata storage, or any custom data pipeline parts. On top of that they won't be able to implement their own specialized (master) client logic (e.g. linked list stuff, deduped content).

**Comment by GlenDC** [comment]
For now I implemented it as proposed and approved in https://github.com/zero-os/0-stor/issues/429#issuecomment-354196515.

In beta-3 we can than work on a redesign to hopefully help us further improve the 0-stor client API, and if possible, lock it down (to at least the extent that existing features/API won't be removed).
