### ISSUE TITLE
investigate colfer as an alternative binary format to gogoprotobuf

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#438]
Currently we use https://github.com/gogo/protobuf as a serialization format, for both metadata, as well as for the serialization format used with GRPC.

This was the conclusion and recommendation after going through https://github.com/alecthomas/go_serialization_benchmarks and talking to some people.

However on those listed benchmarks it seems colfer (https://github.com/pascaldekloe/colfer) is not doing bad either. It seems to allocate a ~116% the amount of memory when unmarshalling, compared to gogo-protobuf, but during marshalling they allocate the same amount of memory. Speed-wise, colfer is however doing better. When running the benchmarks myself I get the following results:

```
BenchmarkGogoprotobufMarshal-4           	10000000	       172 ns/op	      64 B/op	       1 allocs/op
BenchmarkGogoprotobufUnmarshal-4         	 5000000	       245 ns/op	      96 B/op	       3 allocs/op
BenchmarkColferMarshal-4                 	10000000	       142 ns/op	      64 B/op	       1 allocs/op
BenchmarkColferUnmarshal-4               	10000000	       199 ns/op	     112 B/op	       3 allocs/op
```

Colfer seems to marshal in ~70% of the time that gogo-protobuf takes, and it seems to unmarshal in ~71% of the time that gogo-protobuf takes.

As a first step we should probably make sure that both libraries and generation tools are up to date, and re-run those benchmarks once again. We should also check if there aren't any improvements we can make to both the schemes used (as both colfer and protobuf use data schemes that have to be pre-generated) as well as the code in the benchmark file.

If it does indeed turn out that Colfer is faster, I think we should use that where we can. We can use it both for marshaling our metadata, as well as for the GRPC encoding format (as grpc allows alternative encoding formats).

But before we lock down on that, we should add some benchmarks once colfer is implemented in our codebase, and see how it compares to the already implemented gogo-protobuf implementation.

Lastly, even if we end up going for colfer as our (default) encoding format. It doesn't have to mean that we throw away gogo-protobuf, as that last one is still really fast as well. We could have them live side-by-side, and allow the user to switch to gogo-protobuf none the less should they wish.

But first things first, we should start by ensuring those benchmarks are indeed as correct as they can be, as well as representative for our use cases.

**Comment by GlenDC** [comment]
Besides colfer and gogoprotobuf there doesn't seem do be anything better at the moment. Not in those benchmarks, and neither elsewhere, from what I could find.

I also investigated a bit about RPC protocols, and GRPC seems to be the fastest one available at the moment. If we make our own specialized protocol, just for our use-case, we might be able to increase that performance, but I'm not too sure we want to do that, as that would be a lot of work as well, and GRPC is already fast from what I can see. On top of that I'm fairly sure that in that area, the connection of speed will still always be the bottle-neck, as long as the serialization/encoding protocol is fast.

**Comment by lafont-e** [comment]
Have been reviewing both packages, and the very first thing I see is that colfer depends on some C and C++ files, protobuf does not seems to depend on external code. This alone is the excuse needed to decide for protobuf, as cgo and derivatives normally screw pprof. So if speed seems right or similar, there are no need to change the library.

**Comment by GlenDC** [comment]
The difference is anyhow minimal, and I have more faith in gogo/protobuf, as I know it's used by quite some bug users. So if you now tell me that colfer depends on CGO, than I'm ok to just close this issue as wontfix. But I'll leave it up to you to make the call on it, as you've been looking into it.

**Comment by lafont-e** [comment]
I also trust protobuf much more that I will ever do with collfer. Google has infinitely more resources to correct bugs and enhance performance.
Please close this issue, there are no meaning on changing libraries.

**Comment by GlenDC** [comment]
I did tell you before we do not use http://github.com/golang/protobuf, we use http://github.com/gogo/protobuf, which is compatible with protobuf, but different maintainers, and much faster.

**Comment by GlenDC** [comment]
But yes ok, for now let's close this issue as wontfix, the difference seems to small to risk the potential costs.
