### ISSUE TITLE
figure out a way to test without spawning servers over TCP

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#440]
Currently we spawn our servers on actual TCP ports when running tests which test the full server-client flow. However it should be possible do do this without having to spawn actual servers over TCP, and instead keep it all in-memory, speeding up the unit tests.

For `http` there is the `httptest` pacakge, sadly not really helpful to us. We might be able to use something like https://golang.org/pkg/net/#Pipe, but perhaps/probably not. Need to investigate this. Either way, there should be a way in doing this without having to bind to TCP. This will make everything faster (in the context of testing), making it easier to test and decreasing the feedback loop time of travis CI.

**Comment by lafont-e** [comment]
I did take a look at httptest and seems quite easy to change "tcp" protocol for just "unixgram" (ie: file sockets) there are a private functions that creates the listener with "tcp", we just change it to "unix", but as it's a private funcion, you just need to rewrite 2 public functions, something like

```
var unixserve = flag.String("httptest.serve", "", "if non-empty, httptest.NewServer serves on this address and blocks")

func NewUnixServer(handler http.Handler, address string) *Server {
	ts := NewUnstartedUnixServer(handler, address)
	ts.Start()
	return ts
}

func NewUnstartedServer(handler http.Handler, address string) *Server {
	return &Server{
		Listener: newLocalUnixListener(address),
		Config:   &http.Server{Handler: handler},
	}
}

func newLocalUnixListener(address string) net.Listener {
	port, err := ioutil.TempFile(os.TempDir(), prefix string)

	if *unixserve != "" {
		port = *unixserve
	}

	l, err := net.Listen("unix", port.Name())
	if err != nil {
		panic(fmt.Sprintf("httptest: failed to listen on %v: %v", port.Name(), err))
	}
	return l
}
```

The other option is to use the [__httpunix__](https://godoc.org/github.com/tv42/httpunix) package  that already does what we want, well maybe we should add some functions to to make it more httptest like, but this is a good starting point.

**Comment by zaibon** [comment]
I like your first solution. I don't think it's worth it to bring another dependency for just what httpunix brings.

**Comment by GlenDC** [comment]
I do also want to prevent the use of file I/O, there should be no need for that. I also do not want to use unix ports. If we use any of these we can just as well keep using TCP for our tests...

Also we really shouldn't start relying on unix sockets, for tests, as that would make some platforms pretty much not testable using our unit tests.

As stated in the issue request, I want to be able to stay completely in memory. So that we can simply pipe the server to the client directly. On the server-side that should be really do-able as all it cares about is that it receives a valid `net.Listener`, see for example https://godoc.org/github.com/zero-os/0-stor/server/api/grpc#Server.Serve

On the client side you'll need to be able to provide a valid `net.Conn` as that is what you can make the client side use, using https://godoc.org/google.golang.org/grpc#WithDialer.

I do think it makes sense to provide this as a sub-package of 0-stor right now. In the future we can always promote this to its own package should we see that it's also useful for other projects, but for now we can just have it as a sub-package. I don't think there's a project out there that can help us achieve this, I haven't really searched though, but I certainly can't think of one that I know of.

**Comment by lafont-e** [comment]
Some measures

Using github.com/rigtorp/ipc-bench on my machine FX-8320e

```
(✓) enric@GA-990FXA-UD3 ~/Code/c/netBench $ ./unix_thr  4096 1000000
message size: 4096 octets
message count: 1000000
average throughput: 479271 msg/s
average throughput: 15704 Mb/s

(✓) enric@GA-990FXA-UD3 ~/Code/c/netBench $ ./tcp_thr  4096 1000000
message size: 4096 octets
message count: 1000000
average throughput: 166538 msg/s
average throughput: 5457 Mb/s
```

iperf gives similar results for localhost/tcp connections

About latency

```
(✓) enric@GA-990FXA-UD3 ~/Code/c/netBench $ ./tcp_lat  4096 1000000
message size: 4096 octets
roundtrip count: 1000000
average latency: 14745 ns

(✓) enric@GA-990FXA-UD3 ~/Code/c/netBench $ ./unix_lat  4096 1000000
message size: 4096 octets
roundtrip count: 1000000
average latency: 8151 ns
```
* it should be noted, that these tests are being done using localhost, ie: both tcp or uds are using kernel memory to move data.
* it is UDS faster than TCP?, **yes**
* Will it improve test times? **Depends, only if the tests moves a lot of data or a lot of calls, otherwise the difference would be negligible**

If tests are slow to execute, maybe we should look elsewhere, as changing communications for a test hardly are going to make a difference.

**Comment by GlenDC** [comment]
As there isn't really a big improvement when switching communication protocols, and as we aren't really suffering anyway from slow tests, I'm closing this issue as wontfix.

Only if there would have been a do-able, and safe way, to keep it all in-memory and within the program namspace, and by doing so improving the speed by a very significant amount (for our low data transfers), I would approve the continuation of this research.

But for now it seems like a dead-end has been reached.
