### ISSUE TITLE
turn namespace pos. arg into a flag for zstor namespace commands

### ISSUE THREAD

**Issue by lafont-e** [zero-os/0-stor#457]
Currently the namespace argument is a required positional argument for all zstor namespace commands, even though it is already given as part of the config file.

> TLDR: simply add a Persistent string (namespace) flag to the namespace command, and remove the positional namespace argument from all of those commands. if that flag is given, use that namespace, otherwise use the one given in the config, if none is given anywhere return an error

However it might still be useful to be able to define a namespace other than the one defined in the config file, without having to rewrite the config file each time. Therefore we should also provide an optional `--namespace` flag, which would overwrite the namespace given in the config file.

This would make the `zstor commands` look like following:

```
Manage namespaces and their permissions.

Usage:
  zstor namespace [command]

Available Commands:
  create      Create a namespace.
  delete      Delete a namespace.
  permission  Manage permissions of namespaces.

Flags:
  -h, --help   help for namespace
      --namespace string   an optional namespace (label) to overwrite the config define one

Global Flags:
  -C, --config string   Path to the configuration file. (default "config.yaml")
  -D, --debug           Enable debug logging.
  -J, --jobs int        number of parallel jobs to run for tasks that support this (default 8)
```

```
Create a namespace.

Usage:
  zstor namespace create [flags]

Flags:
  -h, --help   help for create

Global Flags:
  -C, --config string      Path to the configuration file. (default "config.yaml")
  -D, --debug              Enable debug logging.
  -J, --jobs int           number of parallel jobs to run for tasks that support this (default 8)
      --namespace string   an optional namespace (label) to overwrite the config define one
```

```
Delete a namespace.

Usage:
  zstor namespace delete [flags]

Flags:
  -h, --help   help for delete

Global Flags:
  -C, --config string      Path to the configuration file. (default "config.yaml")
  -D, --debug              Enable debug logging.
  -J, --jobs int           number of parallel jobs to run for tasks that support this (default 8)
      --namespace string   an optional namespace (label) to overwrite the config define one
```

```
Set permissions for a given user and namespace.

Usage:
  zstor namespace permission set <userID> [flags]

Flags:
  -a, --admin    Set admin permissions for the given user and namespace.
  -d, --delete   Set delete permissions for the given user and namespace.
  -h, --help     help for set
  -r, --read     Set read permissions for the given user and namespace.
  -w, --write    Set write permissions for the given user and namespace.

Global Flags:
  -C, --config string      Path to the configuration file. (default "config.yaml")
  -D, --debug              Enable debug logging.
  -J, --jobs int           number of parallel jobs to run for tasks that support this (default 8)
      --namespace string   an optional namespace (label) to overwrite the config define one
```

```
Get permissions for a given user and namespace.

Usage:
  zstor namespace permission get <userID>  [flags]

Flags:
  -h, --help          help for get
      --json          Print the permissions in JSON format instead of a custom human readable format.
      --json-pretty   Print the permissions in prettified JSON format instead of a custom human readable format.

Global Flags:
  -C, --config string      Path to the configuration file. (default "config.yaml")
  -D, --debug              Enable debug logging.
  -J, --jobs int           number of parallel jobs to run for tasks that support this (default 8)
      --namespace string   an optional namespace (label) to overwrite the config define one
```

**Comment by GlenDC** [comment]
In a future release we'll take a look at all flags, configs and how we do configuration in general. But that is work done as part of #422 and outside the scope of this issue.

**Comment by zaibon** [comment]
I don't see the use of adding a namespace flag for the namespace commands. It's nartural to use positional argument for this group of command.

What would be useful on the other hand is having this flag for the file group of command.
So you could upload file to different namespace without editing the configuration (considering you use same config for both namespace).

**Comment by GlenDC** [comment]
For me it's the same, you could add it to both the namespace and file commands. Because both of them still use the config as well (e.g. for IYO). So your argument doesn't hold up completely. The only way a pos arg is natural, imho, is if it's required by the user, which isn't true for the namespace (label) in the namespace commands, as it could easily be taken from the config.

**Comment by GlenDC** [comment]
For file commands the namespace can now also be overridden, thanks to commit 3096c60. See that commit for a full explanation.
