### ISSUE TITLE
Namespace are not linked to users

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#46]
When creating a namespace, we should also save the user that created the namespace.
So when listing namespaces, only the namespace the user has access to are listed.

**Comment by despiegk** [comment]
think this is wrong, namespace should not be linked to users.
there can be more than 1 user dealing with namespaces.

its ok to see all namespaces, you need to have permission but that is what the reservations & secrets resolve I think??

**Comment by zaibon** [comment]
New solution regarding namespace.
We'll use IYO group feature to create namespace.

So, in IYO, if you are part of a group called `0store.mygroup`, then you will have accesss to namespace `mygroup`

Using JWT, we can verify that a user is part of that group and thus have access to get namespace
