### ISSUE TITLE
investigate use of twirp as rpc framework for zstordb server/client connections

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#472]
https://github.com/twitchtv/twirp

**Comment by GlenDC** [comment]
Could be another alternative for the current GRPC connections, as well as the #469 proposal.

**Comment by GlenDC** [comment]
The only problem with twirp is that it's Go-only, so it could only really be used for our zstordb server<->client (internal) connection.

Further I can't say too much yet, as I have no experience with twirp, nor did I do any research.

**Comment by iwanbk** [comment]
we don't have the server anymore
