### ISSUE TITLE
Humanize benchmark result numbers

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#485]
Currently all the result numbers are given in bytes. 
It hard to read when having big number, would be nice to be able to humanize these results number.
something like : https://github.com/jmoiron/humanize

**Comment by GlenDC** [comment]
Already fixed for beta-2 by @katia-e I think, in commit 91cde0bf3b5ea5ed25847adf623e0ecd24067d74.

Still needs to be merged in for master though, as part of PR #476.

**Comment by GlenDC** [comment]
Now also in master, as b1801c59d7770cd81f2c5f9087dd70eb1f519a8e.
