### ISSUE TITLE
user defined metadata

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#503]
It would be cool if 0-Stor could support user defined metadata.

We could use it to store content-type, content-encoding, etc.

S3 docs about user defined metadata : https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata

**Comment by GlenDC** [comment]
Already a feature that was planned before as part of issue #424.

**Comment by iwanbk** [comment]
My proposal:

**metadata**

Add `UserDefined` (or other better name)  field to https://godoc.org/github.com/zero-os/0-stor/client/metastor/metatypes#Metadata, this field is used to store the user defined metadata in raw format. The encoding of user defined metadata is up to the user.

**client API**

Add another write method to   to https://godoc.org/github.com/zero-os/0-stor/client#Client, with user defined metadata (in raw string) as additional argument.
Not sure about the name, maybe `WriteWithUserMeta` or `WriteWithMeta`
```go
func (c *Client) WriteWithUserMeta(key []byte, r io.Reader, userMeta string) (*metatypes.Metadata, error)
```

What do you think @zaibon @GlenDC ?

**Comment by GlenDC** [comment]
Yeah that's indeed more or less how I had in mind since the beginning as well, except that I had other type signatures in mind:

```
UserDefined map[string]interface{}
```

```
map<string, Any> userDefined = 10;
```

You would have to convert between `Any` and `interface{}`, but at least you would do it automatically for the user and with some information attached to it which identifies the serialized value.

**Comment by iwanbk** [comment]
Sounds good for me

**Comment by zaibon** [comment]
Ok I like how simple this looks.
So that means that any implementation of the metastor interface will need to support this `UserDefine` type, right ?

**Comment by GlenDC** [comment]
> So that means that any implementation of the metastor interface will need to support this UserDefine type, right ?

Not sure what you mean, as that will be simply part of https://godoc.org/github.com/zero-os/0-stor/client/metastor/metatypes#Metadata, and thus nothing changes to the metastor client interface.

I suppose you mean serialization/deserialization wise. But that is also not true as the serialization/deserialization logic is centralized (for proto) as https://godoc.org/github.com/zero-os/0-stor/client/metastor/encoding/proto#MarshalMetadata and https://godoc.org/github.com/zero-os/0-stor/client/metastor/encoding/proto#UnmarshalMetadata.

There we would just need to make sure we support all the usual primitive types as well as expected (fallback) interfaces.

**Comment by iwanbk** [comment]
> map<string, Any> userDefined = 10;

It seems we can't do this, because `Any` is not converted to `interface{}`, but `ptypes.Any`
https://godoc.org/github.com/golang/protobuf/ptypes/any

**Comment by GlenDC** [comment]
We don't use `google/protobuf` though, but `gogo/proto`. Where I would expect it is converted to https://godoc.org/github.com/gogo/protobuf/types#Any. And this is OK.

Because remember, the marshal/unmarshal is centralized in a single location. So after you unmarshalled the proto values into the Golang `Any` type, you can than convert it to the correct type, and store it in your `map[string]interface{}`, all this is done for the user behind the API screens.

**Comment by iwanbk** [comment]
**unmarshall**

We need to convert `Any` to `interface{}`, 
The best method i can found so far is 
```go
GetValue() []byte
```
 https://godoc.org/github.com/gogo/protobuf/types#Any.GetValue. Which returns byte representation of the `Any`.

**marshall**
we need to convert `interface{}` to `Any`.

From the test code, it seems we can do by doing
```go
&Any{
 Value: byteSliceRepresentationOfTheInterface{}
}
```

If what i wrote above is indeed the right way, then it seems that using `Any` is not the good choice. Because we always need to get the `[]byte` representation of the `interface{}`.

**Comment by iwanbk** [comment]
please also note that we need to iterate the map each time we do marshal/unmarshal

**Comment by GlenDC** [comment]
................

You need to use also the second property of Any, as that defines the type it was stored as. This way you can convert your binary data to the actual type and store that as `interface{}`.

**Comment by iwanbk** [comment]
>  it seems that using Any is not the good choice. Because we always need to get the []byte representation of the interface{}.

This is the main point why i don't like to use `map[string]interface{}`. 

With using  `interface{}`, it means we need to support all types. The problem is getting the `[]byte` representation of a type. There is no problem for `string`, `[]byte`, or number. But how about `slice` or even `map`?

So, i propose to use `map[string]string` instead of `map[string]interface{}`, let the user do their own encoding if they want to support complex type.

**Comment by GlenDC** [comment]
@iwanbk that's a solved problem. It's called interfaces. Users can ensure that their type supports https://godoc.org/encoding#BinaryMarshaler and the unmarshaler equivalent. A users would do this when:

+ they want to override the default encoding of (indirect) primitive types (integers, strings, byte slices, boolean);
+ they want to support complex types that could otherwise not (reasonable) be supported (structs, maps, multidimensional slices, non-byte slices, ...);

There is a reason these generic encoding interfaces exist. It's exactly to allow people to define their own encoding.

Storing it as a `map[string]string` is ridiculous as people would have to _always_ decode and encode their own types explicitly, each time they get/set the data. This is especially stupid if you know that most of the time people will use primitive types as properties.

**Comment by GlenDC** [comment]
Also, why is there still not a reasonable PR for this feature, seems like it's simple enough to support it, or are you mostly working on other projects @iwanbk?

**Comment by iwanbk** [comment]
> This is especially stupid if you know that most of the time people will use primitive types as properties.

Yeah, i agree

> seems like it's simple enough to support it

Yep, simple for you, not for me.
I personally still not sure with the best way to handle this `interface{}`.
(you might already know from my previous questions)

Feel free to take it over.

>  or are you mostly working on other projects @iwanbk?

This morning i checked this issue for a while, then working on minio, will still work on it in few hours and will be back to this issue after that

**Comment by GlenDC** [comment]
> Feel free to take it over.

I would love to, sadly no time.

> I personally still not sure with the best way to handle this `interface{}`

Let me try to explain what I have in mind. I'm going to explain just for marshaling, as unmarshmaling is  easy enough once you understand the marshaling.

If we look at https://github.com/zero-os/0-stor/blob/d1160298e98f8dd39ddff0c20fe6bec67196b7f1/client/metastor/encoding/proto/proto.go#L25-L53, this is where the marshaling happens (unless you guys use your own marshaler/unmarshaler pair, in which case it will look like that more or less.

It's in this location you would convert our `map[string]interface{}` to the `string->Any` hashmap of proto.

Always to make sure to go from indirect to direct types first, as to be able to map to the correct type. First you would than check if they support the `BinaryMarshaler` interface, if they do just use that one. If they don't try to switch over the primitive types that we can reasonably support. If not any of these either you can exit with an error.

Each time you will marshal the value to a binary value, how depends on the type, and than also make sure to use the correct TypeURL. Use standard ones (if they exist) when possible. These type URLs are very important, as they are used to identify the correct type these values have to be marshaled to. 

Should it be not efficient or too complex to automatically interfer all the real types (not the interface types), than there might be another approach we can take, which you might prefer.

We could in that other approach indeed use `map[string][]byte`, in that case we don't have to do anything special for the marshaling, as `proto` can map that directly.

It's harder to use though. We would need to think on how we could make it work. Perhaps we can provide utility functions which can allow for a `map[string]interface{}` <-> `map[string][]byte` conversion.

**Comment by GlenDC** [comment]
Based on my last comment, I came up with an approach that could work nice with Golang, while remaining sane enough for other languages (should they ever become used).

In the metadata proto scheme we simply use it as a regular `map[string][]byte`, however in Golang (https://godoc.org/github.com/zero-os/0-stor/client/metastor/metatypes#Metadata) we would use it as `map[string]interface{}`. Than in the encoding package (https://godoc.org/github.com/zero-os/0-stor/client/metastor/encoding) we would implement utlity functions to encode our Golang representation of the custom metadata (https://godoc.org/github.com/zero-os/0-stor/client/metastor/metatypes#Metadata) to a `map[string][]byte` representation (and vise versa).  In those functions we would support just primitve types, as well as the BinaryMarshaler/Unmarshaler types I mentioned earlier. It's important to give those binary interfaces priority so people can overwrite also the primitive types we support, and not just as to support complex types.

The beauty of this idea is that:

+ users (including us) would never have to worry about the encoding/decoding themselves (except for implementing the BinaryMarshal/Unmarshal interfaces when needed), as those custom-metadata-encoding/decoding util functions will be automatically used by us in the `proto` encoding package, as part of the marshal/unmarshal process there.
+ by having it as separate util functions, anyone can use it as well, should they implement their own metadata encoding/decoding;

**Comment by iwanbk** [comment]
> while remaining sane enough for other languages (should they ever become used).

How it will work for other language? We need it for (at least) python too, as daemon's client.

> This is especially stupid if you know that most of the time people will use primitive types as properties.

Yeah, this is true, but by using the `interface{}` instead of `string` we are really forced to support any types, and then might end up implements useless things.

Just FYI, i checked user's metadata type of some storage servers, all info i found are using `map[string]string`
- minio : https://godoc.org/github.com/minio/minio-go#Core.PutObject
- azure: https://godoc.org/github.com/Azure/azure-sdk-for-go/storage#BlobMetadata
- google cloud storage: https://godoc.org/cloud.google.com/go/storage#ObjectAttrs
- amazon s3 : https://godoc.org/github.com/aws/aws-sdk-go/service/s3#PutObjectInput

**Comment by zaibon** [comment]
https://github.com/zero-os/0-stor/pull/526
