### ISSUE TITLE
questions for specs

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-stor#51]
following questions to address asap

- content is expected to be dedupe or not (originally was not intended like this)
- namespaces can have overlapping names, how to deal with this (for different users)
- do we allow overwrite of data (same key)? if not then there is only delete & add
- do we allow user to manipulate the reference list him self, or do we need to implement the logic
- do we use IYO? what is benefit and downside if we do (was not intended like this) there was no notion of user only a 16 byte id, which was the identification of the user
- do we use JWT, why yes or no (was not intended like this)

**Comment by despiegk** [comment]
if you guys believe we need things like JWT or IYO lets discuss why

**Comment by zaibon** [comment]
> content is expected to be dedupe or not (originally was not intended like this)

We don't expect any data format from the user. But on the disk, if 2 user send same key-value pair, we update reference list of this data. 
If 2 user try to set same key with different content, second write is rejected. So no overwrite possible

> namespaces can have overlapping names, how to deal with this (for different users)

Indeed the case, How should we tackle that ? open issue for it:  https://github.com/zero-os/0-stor/issues/46

> do we allow overwrite of data (same key)? if not then there is only delete & add

We don't refer to first question.

> do we allow user to manipulate the reference list him self, or do we need to implement the logic

We don't allow user to directly deal with reference list. this is done transparently trough write and delete

> do we use IYO? what is benefit and downside if we do (was not intended like this) there was no notion of user only a 16 byte id, which was the identification of the user

Now we expect a IYO JWT with the scope user:name and we use this ID in the reference list. 
If we want to avoid IYO, it's easy to change. but then how do we ensure security, anyone can create any user ID. Is this the intended way of working ?

> do we use JWT, why yes or no (was not intended like this)

Yes, currently the reservation token and data token are JWT. But this is still only a string at then end. Just that the string holds some info and is signed so we can validate it.
These JWT are generated by the 0-stor, not IYO.
There is a choice here. If we use JWT, we have save a hit to the db cause we can just validate the data by verifiying the JWT. 
If we don't use JWT, then we need to save the tokens in db, and compare it for each data access. 
Don't know which one is faster, going to the db, or some crypto verification.

**Comment by zaibon** [comment]
We did a call with @despiegk  and @FastGeert regarding these questions, I'll update the spec accordingly.
Can follow up on that in this issue : https://github.com/zero-os/0-stor/issues/53
