### ISSUE TITLE
implement DB interface on top of 0-db

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#514]
Now that [0-db](https://github.com/zero-os/0-db) as the required feature we should try to implement the DB interface on top of it so we could also use 0-db as database for zstordb

We should also start thinking how we're going to integrate that in the configuration. Since 0db is not embeded yet, we need to provide connection info

**Comment by zaibon** [comment]
last week I played a bit with 0-db and starter implementing the interface, but 0-db changed a bit since then.
work I did can be found on https://github.com/zero-os/0-stor/tree/zdb

**Comment by GlenDC** [comment]
> We should also start thinking how we're going to integrate that in the configuration. Since 0db is not embeded yet, we need to provide connection info

That would be the server configuration I suppose. Perhaps there could be an optional flag, which takes an address. This way you can use a (local?) 0-db database instead of badgerdb.

Is it planned to provide a Golang interface (using cgo)?

**Comment by zaibon** [comment]
> That would be the server configuration I suppose. Perhaps there could be an optional flag, which takes an address. This way you can use a (local?) 0-db database (over a unix socket?) instead of badgerdb.

yes indeed

> Is it planned to provide a Golang interface (using cgo), perhaps not for now, but a future milestone?

it is planned, but don't think this will be done for this milestone.

**Comment by GlenDC** [comment]
> it is planned, but don't think this will be done for this milestone.

As 0-db will always require separate binaries, I do think that no matter what we do, it should always be an opt-in option, with badgerdb remaining the default one. This way we can always ensure that zstordb runs on any platform for anyone, with a very easy install and usage.

**Comment by zaibon** [comment]
I was also looking at the DB interface itself, it seems we don't use the `Set` method anymore anywhere in the 0-stor code base, maybe while we're at it we should clean this up.

Also, @maxux can you explain a bit or point to documentation on how the 0-db works when it doesn't keep index in memory, cause I think that's what you want to use for 0-stor.
If that's the case we'll have to update the DB interface and probably the Metadata struct to be able to keep the info return by 0-stor after a set

**Comment by maxux** [comment]
The index-free mode is called `direct-key` mode, small information about it here: https://github.com/zero-os/0-db#direct-key

Basicly, you do some `SET` request, without providing the key, and the response will contains the key (in this case, it's `6 binary bytes`). More will comes with namespace support, which will be discussed soon.

**Comment by GlenDC** [comment]
> I was also looking at the DB interface itself, it seems we don't use the Set method anymore anywhere in the 0-stor code base, maybe while we're at it we should clean this up.

Sure, that sounds like an excellent idea. As that database interface is not really meant for usage other than our zstordb code, I think it's fine to clean that up and keep that interface to a minimum. Go for it.

(will impact quite some unit tests though, so make sure to update those correctly)

**Comment by zaibon** [comment]
https://sourcegraph.com/github.com/zero-os/0-stor/-/blob/server/db/db.go#L39:2$references
This gives you all the reference where we use the Set

**Comment by zaibon** [comment]
> If that's the case we'll have to update the DB interface and probably the Metadata struct to be able to keep the info return by 0-stor after a set

Forget that, the key return by direct-key already contain everything it needs to get the data back.
> 6 bytes: 2 bytes pour le fileid, 4 bytes pour l'offset

So no need to change the interface, even better :-)

**Comment by GlenDC** [comment]
Très bien :)

**Comment by zaibon** [comment]
not needed because of #515
