### ISSUE TITLE
Drop zstordb and use 0-db instead

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#515]
After a discussions with @maxux and @despiegk regarding 0-db integration as backend for zstordb, it comes out that if 0-db already provide and network interface, zstordb doesn't really need to exists anymore since it's only job is to expose badger over grpc.

So instead of #514, what should happens is updating the client side of 0-stor to talk the protocol of 0-db.
Doing this will also allow us to close #504 #499 #488 #487 #352  cause all of these will be provided by 0-db.

There will be some change regarding how namespaces are created though.
With reservation in mind, the way how it will works is:
- a user reserve some storage space
- a 0-robot will received this reservation through the blockchain
- 0-robot contacts the 0-db running on top of the disk on the nodes and create a namespace on all the 0-db concerned. Creation of a namespace include the quota the 0-db can use on top of the disk
- the creation of a namespace return a secret that need to be used by the 0-stor client to authenticate for that namespace

**Comment by iwanbk** [comment]
> Doing this will also allow us to close #504 #499 #488 #487 #352 

This is not true for #499(read with offset & length) because the object are likely to be processed (compress, encrypt, split) and 0-db has no idea about the processing.

**Comment by GlenDC** [comment]
> This is not true for #499(read with offset & length) because the object are likely to be processed (compress, encrypt, split) and 0-db has no idea about the processing.

As we first split our data up, we should be able to implement the functionality to fetch (and decode+) the chunks we need, and nothing more. This is possible as all our chunks have a fixed maximum size, where I guess only the last chunk can be of a smaller size. Therefore computing the min and max points is trivial. This would require us to add the ChunkSize to the metadata though, which could default to `0` in case there is no Chunking done.

Doing this we could add the extra methods required to fetch a partial raw object. I would have this as separate methods, as I think in most use cases you'll still want to read the entire object.

So feel free to work on a solution for issue #499 as well.

**Comment by iwanbk** [comment]
> I also don't mind adding the feature myself quickly, should you be swamped as well @iwanbk.

forgot to reply to this, yeah, please do.

**Comment by zaibon** [comment]
@iwanbk can you take care of this one, @GlenDC needs to focus 100% on rivine.

**Comment by GlenDC** [comment]
I'm bound to chains :(

**Comment by iwanbk** [comment]
> @iwanbk can you take care of this one, @GlenDC needs to focus 100% on rivine.

Okay

What is `Chunk.Size` in https://godoc.org/github.com/zero-os/0-stor/client/metastor/metatypes#Chunk?
Is it the storage size or the actual size?
I guess it is the storage size

> As we first split our data up, we should be able to implement the functionality to fetch (and decode+) the chunks we need, and nothing more

So, are you saying that if we have `blockSize=4096` and we want to read from `offset=5000`, we can simply fetch and decode from 2nd chunck?

> This would require us to add the ChunkSize to the metadata though, which could default to 0 in case there is no Chunking done.

can't we simply do it with
```go
len(metatypes.Metadata.Chunks
```

Sorry if my question doesn't make sense, i didn't read the code yet.

**Comment by GlenDC** [comment]
> I guess it is the storage size

yes

> So, are you saying that if we have blockSize=4096 and we want to read from offset=5000, we can simply fetch and decode from 2nd chunck?

yes

> len(metatypes.Metadata.Chunks)

No, that would simply get the amount of chunks, we need to store the chunk size (what you just called `blockSize` to the root config, which indicates the size that we've split the data up at, which is a value that applies for all chunks. This way we can compute the first and last index of chunks to read. And thus will we only have to fetch and decodes as little chunks as required. We'll still have to manually slice the decoded output of the first and last decoded chunk to come to the real offset and size however, but that cannot be avoided.

**Comment by GlenDC** [comment]
What is still left to be done for this issue, it is finished, no?
