### ISSUE TITLE
Review namespace management

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#517]
as part of #515 we need to review the all namespace management.
When using 0-db the namespace concept won't use IYO anymore.
The namespace is something that is going to be created on each data shard, usually by another process then the 0-stor client itself, even if I think we should still have some method to so so from the client.

Once a namespace has been created on each shard, 0-stor client will receive a secret to authenticate against the 0-dbs and allow to access a namespace.

Which means the list of shard is going to be a crucial information to keep. It was already before cause the configuration of the pipeline, but here it also going to be used to know on which shard the namespace can be found. Even though, if we have some shard listed where the namespace doesn't exist, then can just be skipped after authentication if it turns out the namespace doesn't exist on a shard, but that's detail.

So what has to be done:
- Remove "github.com/zero-os/0-stor/client/itsyouonline" package, won't be needed anymore
- When client is created, it should contact all 0-db and send an AUTH command with the namespace and secret he will be accessing. This will open a tcp connection that will be used for all read/write operation
- Update configuration to remove any trace of IYO, so organization, app id and secret

**Comment by GlenDC** [comment]
> Remove "github.com/zero-os/0-stor/client/itsyouonline" package, won't be needed anymore

If we remove this, we can also remove the zstordb package(s) and zstordb client, as those all use the IYO package (in)directly. Is that really what you want?

> When client is created, it should contact all 0-db and send an AUTH command with the namespace and secret he will be accessing. This will open a tcp connection that will be used for all read/write operation

Those connections better be secure.

> Update configuration to remove any trace of IYO, so organization, app id and secret

This again implies that the zstordb package(s) and client are to be deleted as well?

**Comment by zaibon** [comment]
> If we remove this, we can also remove the zstordb package(s) and zstordb client, as those all use the IYO package (in)directly. Is that really what you want?

Yes, that's the idea

> Those connections better be secure.

Indeed, this is also foreseen that 0-db will need to implement TLS or exposed behind a proxy that provide this seciruty

**Comment by iwanbk** [comment]
> Remove "github.com/zero-os/0-stor/client/itsyouonline" package, won't be needed anymore

For the existing APIs, we still need to implement it in other package, right?

Regarding the implemnetation:
- `create` & `delete` need to operate on all 0-db shards
- `list` also need to operate on all shards, then combine the result, there are two mode of the combine:
     - only list namespace that exist  in all shards
    - list all namespaces found
- `get` operates on all shards, and combine the result, still not sure how.
   - creation date : choose the earlies date
   - number of objects : choose the biggest number

**Comment by zaibon** [comment]
> create & delete need to operate on all 0-db shards

These operation needs ADMIN rights on the 0-dbs, which in practice is nearly never going to be the case.

> List

can be done too, but in practice from a client point of view, it is probably better for the client to rely on its metadata to know which namespace he has. But beeing able to list the namespaces on a 0-db can be something we want to do

> get

Or we can also have a Get Namespace that only operate on a single shard, so it is up to the user to combine as we wants.

**Comment by iwanbk** [comment]
> it is probably better for the client to rely on its metadata to know which namespace he has

You mean the client's own metadata, right? 
Because i'm not aware that we have or plan to have this feature in 0-stor metadata

**Comment by zaibon** [comment]
yes. The client is the one that should know about his own namespace.

**Comment by iwanbk** [comment]
> Remove "github.com/zero-os/0-stor/client/itsyouonline" package, won't be needed anymore

I've removed it in `remove-grpc-iyo` branch.
Also removed the gcpc server (zstordb ) and client packages.
Now still checking for the docs, it seems there are many things to be deleted

> The namespace is something that is going to be created on each data shard, usually by another process then the 0-stor client itself, even if I think we should still have some method to so so from the client.

I think it is better for 0-stor to rely solely on the external tool to do it, ideally the tool is part of 0-db itself. So we don't duplicate our work.

We had our own IYO/namespace management package because IYO library is auto generated, not easy to be used.  But i think this won't be the case for 0-db cli because it won't be auto generated.

**Comment by GlenDC** [comment]
> I think it is better for 0-stor to rely solely on the external tool to do it, ideally the tool is part of 0-db itself. So we don't duplicate our work.

I agree with this and the rest of that statement.

**Comment by zaibon** [comment]
yep agree too.  Namespace is going to be bound with capacity reservation, so eventually this information will come from the block-chain itself.

**Comment by iwanbk** [comment]
> yep agree too. Namespace is going to be bound with capacity reservation, so eventually this information will come from the block-chain itself.

Then nothing else to do AFAIK, i think we can close this issue.
