### ISSUE TITLE
review the data structure: in DB & binary

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-stor#52]
- crc vs hash
- reference list
- how stored at backend

please let me see it

**Comment by zaibon** [comment]
On the disk the data are store like describe in the specs : https://github.com/zero-os/0-stor/blob/master/specs/concept.md#format-of-objects-stored-on-disk

But we don't expect any specific format when receiving data from the user.

**Comment by despiegk** [comment]
what tables in DB?
