### ISSUE TITLE
Remove etcd as default metastor

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#531]
As previously discussed on chat:
- remove etcd as default metastor
- add documentation on how to deal with metadata returned after a write
- some example how to implement the metastor interface
- update the documentation to reflect that 0-stor is just a library ( i think it is already done, but need to be checked again)
- example to use existing metastor interface

**Comment by GlenDC** [comment]
What would be the new default than?

**Comment by iwanbk** [comment]
> What would be the new default than?

We don't have, until we have new reliable metastor.
(AFAIK 0-metadata was the candidate, not sure for now.)

We instead provide example to use the existing metastor.

**Comment by iwanbk** [comment]
@GlenDC @zaibon i propose these:

(1) Remove the `client.MetaStorConfig` https://godoc.org/github.com/zero-os/0-stor/client#MetaStorConfig

We won't have default metstor anymore, it makes this `struct` is not useful.

It implies that we have to delete this https://godoc.org/github.com/zero-os/0-stor/client#NewClientFromConfig

(2) Creates new https://godoc.org/github.com/zero-os/0-stor/client#NewClientFromConfig

```go
func NewClientFromConfig(cfg Config, metaClient *metastor.Client, jobCount int) (*Client,error)
```


(3) Change https://godoc.org/github.com/zero-os/0-stor/client/metastor#NewClient to `NewClientFromConfig`

(4) creates new `metastor.NewClient`

```go
func NewClient(namespace []byte, db metastor.db.DB, encryptKey string) (*Client,error)
```
It will creates metastor client with:
- given `db.DB` implementation
- default encoding, which is protobuf
- if `encryptKey` is not empty, use default (aes) encryption

While the old `metastor.NewClient` give powerful way, it is also hard to use.

**Comment by iwanbk** [comment]
> I think we should allow to use etcd if the user wants or any other metastor implementation we have.
So by default, there is no metastor, but if the user wants to use once, it can.

Yep, the user can do it with:
1. creates metastor.db, using existing `badger`, `etcd` implementation, or own implementation
2. creates `metastor.Client` with new `metastor.NewClient` i proposed at point(4)
3. creates 0-stor client with `client.NewClient` or `client.NewClientFromConfig`

We can also creates wrapper for 1 & 2 for our existing implementation, but still not sure how the config will be.

> Which means we probably need to have some different configuration struct to support the different metastor we have.

The problem with this is each metastor.db implemeentation we have, has different config. `etcd` has `shards` , while `badger` has meta & data dir.

**Comment by zaibon** [comment]
From the go API point I don't think there is any problem. It is already possible to compose how we want.

But for the user that only use CLI, we need a way to configure metastor in the config. 
> The problem with this is each metastor.db implemeentation we have, has different config. etcd has shards , while badger has meta & data dir.

Yep exactly, so that's why we need different struct and a way in the config to be able to parse it depending on the meta stor stype

**Comment by GlenDC** [comment]
For the standard json library there exists a RawMessage (https://godoc.org/encoding/json#RawMessage), which allows you to parse values differently depending on some earlier read properties. This is the kind of thing that allows for dynamic config structs.

I'm sure something similar must exist for YAML, as it anyhow is a superset of JSON.

**Comment by zaibon** [comment]
yep that's what I had in mind.

**Comment by iwanbk** [comment]
> It is already possible to compose how we want.

Not sure what you mean by this, `0-stor/client.NewClientFromConfig` can only creates ETCD metastor, no badger support from there.
So, no, we can't compose what we want at the moment

 > But for the user that only use CLI, we need a way to configure metastor in the config.

Hmm yeah, i think we can achieve it with additional proposal proposed at https://github.com/zero-os/0-stor/issues/531#issuecomment-380052735

> For the standard json library there exists a RawMessage 

Yep, you're right, forgot this thing

Another problem with supporting configurable metastor from 0-stor/client package is that the user will need to vendor the etcd & badger packages.
It means the users are forced to vendor/import (a lot of) packages that they don't need and might not wanted at all. 
It already caused issue with minio, which use etcd 2, see https://github.com/minio/minio/pull/5500#issuecomment-366892574

etcd 2 usage might be special case, but grpc itself already a big packages.

**Comment by GlenDC** [comment]
In theory you could move all etcd implementations into separate plugin libraries. For example:

+ zero-os/0-stor-meta-etcd
+ zero-os/0-stor-meta-badger

Perhaps there is better naming possible.

Such that 0-stor only vendors what it needs for its logic (e.g. pipelining) as well as the stuff it needs for the data client (to communicate with 0-db).

It does mean that the library as it is, won't really be useful on its own, out of the box, as you'll always want some kind of meta storage implementation AFAIK.

**Comment by zaibon** [comment]
> Not sure what you mean by this, 0-stor/client.NewClientFromConfig can only creates ETCD metastor, no badger support from there.

If you use the Go API, then you don't have to use this function, but https://github.com/zero-os/0-stor/blob/d1160298e98f8dd39ddff0c20fe6bec67196b7f1/client/client.go#L234

Regarding vendoring, yeah I was thinking the same. Some kind of way to be able to build with/without support for specific metastor. So for minio we could have something clean for them.

> It does mean that the library as it is, won't really be useful on its own, out of the box, as you'll always want some kind of meta storage implementation AFAIK.

That is not true. The metadata is already return to the client, so in practice, you don't NEED a metastor attached to 0-stor. At least this is true if you use the Go API. For the CLI this is probably a problem. although we can already get metadata from CLI too

**Comment by iwanbk** [comment]
> But for the user that only use CLI, we need a way to configure metastor in the config

If we only need this for CLI, then we can include the metastor related config to the `0-stor/cmd/zstor` package instead of `0stor/client`.

This way, `0-stor/client` doesn't required to import etcd & badger.

> so in practice, you don't NEED a metastor attached to 0-stor. At least this is true if you use the Go API. 

In this case, we should change the non-write API to require metadata instead of key, because we can't assume anymore that 0-stor has knowledge about the metadata storage.

**Comment by iwanbk** [comment]
Sorry for slow update, didn't work yesterday.

> If we only need this for CLI, then we can include the metastor related config to the 0-stor/cmd/zstor package instead of 0stor/client.

For now, i moved the https://godoc.org/github.com/zero-os/0-stor/client#MetaStorConfig to `daemon` package. It is also being used by `zstor` command.

This way, the `daemon` and `zstor` could use the existing `db.DB` implementation.

https://github.com/zero-os/0-stor/blob/ec3f876176429afe212ff67737d5dee59eea0421/daemon/config.go#L29-L37

But i just thinking to move the `MetaStorConfig` to `metastor` package, seems better than `daemon` package.

To use existing `db.DB` implementation, i have added new method in separate package

https://github.com/zero-os/0-stor/blob/ec3f876176429afe212ff67737d5dee59eea0421/client/metastor/db/utils/utils.go#L32-L54

So, only user interested in our existing `db.DB` would need to import `etcd`, `badger`, and all it's required packages.

Next:
- implement things proposed at https://github.com/zero-os/0-stor/issues/531#issuecomment-380046577
- remove `key` in non-write methods of 0-stor client, because we can't assume anymore that 0-stor has info about the metadata storage.

**Comment by iwanbk** [comment]
> remove key in non-write methods of 0-stor client, because we can't assume anymore that 0-stor has info about the metadata storage.

Other alternative is to return error if only provide key but doesn't have `metastor.Client`.
It seems to be the better way to go.

**Comment by iwanbk** [comment]
> Other alternative is to return error if only provide key but doesn't have metastor.Client.
It seems to be the better way to go.

Never mind, it is ugly i think.
