### ISSUE TITLE
JSON is not good format to send binary data

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#63]
0-stor is object store, means that it must support storing binary data.

JSON is bad to send binary data because we must encode the binary data to base64 and then decode it upon receive, base64 usage implies:
- more space on the wire (+33%)
- more processing needed

**Comment by iwanbk** [comment]
A better way is to send binary data as request body

**Comment by iwanbk** [comment]
current implementation doesn't encode the binary string, need to be fixed.

**Comment by delandtj** [comment]
just gob it ? (std lib)

**Comment by iwanbk** [comment]
As @Hamdy suggested in chat, better alternative is using multipart/form data. It is efficient, yet don't need much API change

**Comment by zaibon** [comment]
since https://github.com/zero-os/0-stor/issues/191
Not sure this is still relevant and if we should invest time in this issue
