### ISSUE TITLE
client daemon

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#68]

**Comment by zaibon** [comment]
WIP specification for the daemon: https://github.com/zero-os/0-stor/blob/master/specs/daemon.md

**Comment by GlenDC** [comment]
@iwanbk can you take over this issue? I think you'll first have to finish of the daemon spec to make sure the entire design is worked out. Make sure to cover all corners and details. After that you can start implementing I suppose.

**Comment by iwanbk** [comment]
> @iwanbk can you take over this issue?

sure

**Comment by iwanbk** [comment]
a WIP can be found on `proxy` branch:
- partial implementation at https://github.com/zero-os/0-stor/tree/proxy/proxy
- no unit test 
- tested with simple python test file https://github.com/zero-os/0-stor/blob/proxy/proxy/python/main.py

**Comment by GlenDC** [comment]
+ Looks good in general. Added the comments where needed;
+ You can probably start using `spf13/cobra` for the command-line tool library (unless you or someone else objects in #318);
+ While you should probably add some unit tests here and there, I think for the proxy it's much more important that we have a complete and decent end-to-end (system) test suite.
   + This test suite can than also serve as example code of the full API;

**Comment by iwanbk** [comment]
> While you should probably add some unit tests here and there, I think for the proxy it's much more important that we have a complete and decent end-to-end (system) test suite.
> This test suite can than also serve as example code of the full API;

Indeed. i also only tested it with python script so far.
Then we might want to do #15 in the same time with this issue

**Comment by GlenDC** [comment]
Yeah sure why not.

**Comment by GlenDC** [comment]
You can/should use https://github.com/spf13/cobra by the way as the ctl framework

See #318 for more information.

**Comment by GlenDC** [comment]
@iwanbk you'll have to rebase master into your branch and you can than add your daemon GRPC service (spawner) @ https://github.com/zero-os/0-stor/blob/master/cmd/zstor/commands/daemon.go

**Comment by GlenDC** [comment]
I think https://github.com/zero-os/0-stor/blob/b6fa3b70059e8ae5e16d332f409a9472df5449a2/daemon/api/api.go#L3-L9 should be changed to the following interface:

```go
type Daemon interface {
	// Serve the Daemon on the given listener, ...
	Serve(lis net.Listener) error

	// Close closes the daemon
	Close()
}
```

Inspired by the current server API: https://github.com/zero-os/0-stor/blob/8313659df0b32626f8895fbc862c3c096144f740/server/api/api.go#L23-L35

See https://github.com/zero-os/0-stor/issues/430#issuecomment-354337318 for more information/context on why the Server API is as it is currently, and this might also explain why I think it would also serve well as inspiration for the API of the daemon :)
